/* eslint-disable max-len */
import * as React from "react"

const HighCardinality = () => {

  return (
    <>
      <style>
        {`
        /***************************************************
         * Generated by SVG Artista on 9/10/2022, 4:38:12 PM
         * MIT license (https://opensource.org/licenses/MIT)
         * W. https://svgartista.net
         **************************************************/
        
        @-webkit-keyframes animate-svg-stroke-1 {
          0% {
            stroke-dashoffset: 175.21522521972656px;
            stroke-dasharray: 175.21522521972656px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 175.21522521972656px;
          }
        }
        
        @keyframes animate-svg-stroke-1 {
          0% {
            stroke-dashoffset: 175.21522521972656px;
            stroke-dasharray: 175.21522521972656px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 175.21522521972656px;
          }
        }
        
        .svg-elem-1 {
          -webkit-animation: animate-svg-stroke-1 1s ease 0s both;
                  animation: animate-svg-stroke-1 1s ease 0s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-2 {
          0% {
            stroke-dashoffset: 123px;
            stroke-dasharray: 123px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 123px;
          }
        }
        
        @keyframes animate-svg-stroke-2 {
          0% {
            stroke-dashoffset: 123px;
            stroke-dasharray: 123px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 123px;
          }
        }
        
        .svg-elem-2 {
          -webkit-animation: animate-svg-stroke-2 1s ease 0.12s both;
                  animation: animate-svg-stroke-2 1s ease 0.12s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-3 {
          0% {
            stroke-dashoffset: 117.83599853515625px;
            stroke-dasharray: 117.83599853515625px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 117.83599853515625px;
          }
        }
        
        @keyframes animate-svg-stroke-3 {
          0% {
            stroke-dashoffset: 117.83599853515625px;
            stroke-dasharray: 117.83599853515625px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 117.83599853515625px;
          }
        }
        
        .svg-elem-3 {
          -webkit-animation: animate-svg-stroke-3 1s ease 0.24s both;
                  animation: animate-svg-stroke-3 1s ease 0.24s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-4 {
          0% {
            stroke-dashoffset: 175.2154998779297px;
            stroke-dasharray: 175.2154998779297px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 175.2154998779297px;
          }
        }
        
        @keyframes animate-svg-stroke-4 {
          0% {
            stroke-dashoffset: 175.2154998779297px;
            stroke-dasharray: 175.2154998779297px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 175.2154998779297px;
          }
        }
        
        .svg-elem-4 {
          -webkit-animation: animate-svg-stroke-4 1s ease 0.36s both;
                  animation: animate-svg-stroke-4 1s ease 0.36s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-5 {
          0% {
            stroke-dashoffset: 74.97370147705078px;
            stroke-dasharray: 74.97370147705078px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 74.97370147705078px;
          }
        }
        
        @keyframes animate-svg-stroke-5 {
          0% {
            stroke-dashoffset: 74.97370147705078px;
            stroke-dasharray: 74.97370147705078px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 74.97370147705078px;
          }
        }
        
        .svg-elem-5 {
          -webkit-animation: animate-svg-stroke-5 1s ease 0.48s both;
                  animation: animate-svg-stroke-5 1s ease 0.48s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-6 {
          0% {
            stroke-dashoffset: 74.97299194335938px;
            stroke-dasharray: 74.97299194335938px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 74.97299194335938px;
          }
        }
        
        @keyframes animate-svg-stroke-6 {
          0% {
            stroke-dashoffset: 74.97299194335938px;
            stroke-dasharray: 74.97299194335938px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 74.97299194335938px;
          }
        }
        
        .svg-elem-6 {
          -webkit-animation: animate-svg-stroke-6 1s ease 0.6s both;
                  animation: animate-svg-stroke-6 1s ease 0.6s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-7 {
          0% {
            stroke-dashoffset: 175.21524047851562px;
            stroke-dasharray: 175.21524047851562px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 175.21524047851562px;
          }
        }
        
        @keyframes animate-svg-stroke-7 {
          0% {
            stroke-dashoffset: 175.21524047851562px;
            stroke-dasharray: 175.21524047851562px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 175.21524047851562px;
          }
        }
        
        .svg-elem-7 {
          -webkit-animation: animate-svg-stroke-7 1s ease 0.72s both;
                  animation: animate-svg-stroke-7 1s ease 0.72s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-8 {
          0% {
            stroke-dashoffset: 74.97341918945312px;
            stroke-dasharray: 74.97341918945312px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 74.97341918945312px;
          }
        }
        
        @keyframes animate-svg-stroke-8 {
          0% {
            stroke-dashoffset: 74.97341918945312px;
            stroke-dasharray: 74.97341918945312px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 74.97341918945312px;
          }
        }
        
        .svg-elem-8 {
          -webkit-animation: animate-svg-stroke-8 1s ease 0.84s both;
                  animation: animate-svg-stroke-8 1s ease 0.84s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-9 {
          0% {
            stroke-dashoffset: 74.97440338134766px;
            stroke-dasharray: 74.97440338134766px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 74.97440338134766px;
          }
        }
        
        @keyframes animate-svg-stroke-9 {
          0% {
            stroke-dashoffset: 74.97440338134766px;
            stroke-dasharray: 74.97440338134766px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 74.97440338134766px;
          }
        }
        
        .svg-elem-9 {
          -webkit-animation: animate-svg-stroke-9 1s ease 0.96s both;
                  animation: animate-svg-stroke-9 1s ease 0.96s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-10 {
          0% {
            stroke-dashoffset: 175.2156982421875px;
            stroke-dasharray: 175.2156982421875px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 175.2156982421875px;
          }
        }
        
        @keyframes animate-svg-stroke-10 {
          0% {
            stroke-dashoffset: 175.2156982421875px;
            stroke-dasharray: 175.2156982421875px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 175.2156982421875px;
          }
        }
        
        .svg-elem-10 {
          -webkit-animation: animate-svg-stroke-10 1s ease 1.08s both;
                  animation: animate-svg-stroke-10 1s ease 1.08s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-11 {
          0% {
            stroke-dashoffset: 74.97412109375px;
            stroke-dasharray: 74.97412109375px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 74.97412109375px;
          }
        }
        
        @keyframes animate-svg-stroke-11 {
          0% {
            stroke-dashoffset: 74.97412109375px;
            stroke-dasharray: 74.97412109375px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 74.97412109375px;
          }
        }
        
        .svg-elem-11 {
          -webkit-animation: animate-svg-stroke-11 1s ease 1.2s both;
                  animation: animate-svg-stroke-11 1s ease 1.2s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-12 {
          0% {
            stroke-dashoffset: 74.97383880615234px;
            stroke-dasharray: 74.97383880615234px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 74.97383880615234px;
          }
        }
        
        @keyframes animate-svg-stroke-12 {
          0% {
            stroke-dashoffset: 74.97383880615234px;
            stroke-dasharray: 74.97383880615234px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 74.97383880615234px;
          }
        }
        
        .svg-elem-12 {
          -webkit-animation: animate-svg-stroke-12 1s ease 1.3199999999999998s both;
                  animation: animate-svg-stroke-12 1s ease 1.3199999999999998s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-13 {
          0% {
            stroke-dashoffset: 94.5px;
            stroke-dasharray: 94.5px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 94.5px;
          }
        }
        
        @keyframes animate-svg-stroke-13 {
          0% {
            stroke-dashoffset: 94.5px;
            stroke-dasharray: 94.5px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 94.5px;
          }
        }
        
        .svg-elem-13 {
          -webkit-animation: animate-svg-stroke-13 1s ease 1.44s both;
                  animation: animate-svg-stroke-13 1s ease 1.44s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-14 {
          0% {
            stroke-dashoffset: 94.5px;
            stroke-dasharray: 94.5px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 94.5px;
          }
        }
        
        @keyframes animate-svg-stroke-14 {
          0% {
            stroke-dashoffset: 94.5px;
            stroke-dasharray: 94.5px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 94.5px;
          }
        }
        
        .svg-elem-14 {
          -webkit-animation: animate-svg-stroke-14 1s ease 1.56s both;
                  animation: animate-svg-stroke-14 1s ease 1.56s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-15 {
          0% {
            stroke-dashoffset: 94.5px;
            stroke-dasharray: 94.5px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 94.5px;
          }
        }
        
        @keyframes animate-svg-stroke-15 {
          0% {
            stroke-dashoffset: 94.5px;
            stroke-dasharray: 94.5px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 94.5px;
          }
        }
        
        .svg-elem-15 {
          -webkit-animation: animate-svg-stroke-15 1s ease 1.68s both;
                  animation: animate-svg-stroke-15 1s ease 1.68s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-16 {
          0% {
            stroke-dashoffset: 94.5px;
            stroke-dasharray: 94.5px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 94.5px;
          }
        }
        
        @keyframes animate-svg-stroke-16 {
          0% {
            stroke-dashoffset: 94.5px;
            stroke-dasharray: 94.5px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 94.5px;
          }
        }
        
        .svg-elem-16 {
          -webkit-animation: animate-svg-stroke-16 1s ease 1.7999999999999998s both;
                  animation: animate-svg-stroke-16 1s ease 1.7999999999999998s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-17 {
          0% {
            stroke-dashoffset: 94.49946594238281px;
            stroke-dasharray: 94.49946594238281px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 94.49946594238281px;
          }
        }
        
        @keyframes animate-svg-stroke-17 {
          0% {
            stroke-dashoffset: 94.49946594238281px;
            stroke-dasharray: 94.49946594238281px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 94.49946594238281px;
          }
        }
        
        .svg-elem-17 {
          -webkit-animation: animate-svg-stroke-17 1s ease 1.92s both;
                  animation: animate-svg-stroke-17 1s ease 1.92s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-18 {
          0% {
            stroke-dashoffset: 94.49967956542969px;
            stroke-dasharray: 94.49967956542969px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 94.49967956542969px;
          }
        }
        
        @keyframes animate-svg-stroke-18 {
          0% {
            stroke-dashoffset: 94.49967956542969px;
            stroke-dasharray: 94.49967956542969px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 94.49967956542969px;
          }
        }
        
        .svg-elem-18 {
          -webkit-animation: animate-svg-stroke-18 1s ease 2.04s both;
                  animation: animate-svg-stroke-18 1s ease 2.04s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-19 {
          0% {
            stroke-dashoffset: 94.50016784667969px;
            stroke-dasharray: 94.50016784667969px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 94.50016784667969px;
          }
        }
        
        @keyframes animate-svg-stroke-19 {
          0% {
            stroke-dashoffset: 94.50016784667969px;
            stroke-dasharray: 94.50016784667969px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 94.50016784667969px;
          }
        }
        
        .svg-elem-19 {
          -webkit-animation: animate-svg-stroke-19 1s ease 2.16s both;
                  animation: animate-svg-stroke-19 1s ease 2.16s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-20 {
          0% {
            stroke-dashoffset: 94.50025177001953px;
            stroke-dasharray: 94.50025177001953px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 94.50025177001953px;
          }
        }
        
        @keyframes animate-svg-stroke-20 {
          0% {
            stroke-dashoffset: 94.50025177001953px;
            stroke-dasharray: 94.50025177001953px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 94.50025177001953px;
          }
        }
        
        .svg-elem-20 {
          -webkit-animation: animate-svg-stroke-20 1s ease 2.28s both;
                  animation: animate-svg-stroke-20 1s ease 2.28s both;
        }
`}
      </style>
      <svg width="210" height="210" viewBox="0 0 310 291" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M121.344 126.135L157.652 102.536L193.961 126.135L157.652 149.734L121.344 126.135Z" stroke="#6361D1" className="svg-elem-1"></path>
        <line x1="4.37114e-08" y1="126.5" x2="121" y2="126.5" stroke="#6361D1" className="svg-elem-2"></line>
        <path d="M193.664 126.198H309.5" stroke="#6361D1" className="svg-elem-3"></path>
        <path d="M157.5 89.9762L181.099 126.285L157.5 162.594L133.902 126.285L157.5 89.9762Z" stroke="#6361D1" className="svg-elem-4"></path>
        <line x1="157.438" y1="17" x2="157.438" y2="89.9737" stroke="#6361D1" className="svg-elem-5"></line>
        <line x1="157.438" y1="162.296" x2="157.438" y2="235.269" stroke="#6361D1" className="svg-elem-6"></line>
        <path d="M183.066 100.567L174.079 142.928L131.718 151.915L140.705 109.554L183.066 100.567Z" stroke="#26D7A0" className="svg-elem-7"></path>
        <line x1="234.623" y1="48.92" x2="183.023" y2="100.52" stroke="#26D7A0" className="svg-elem-8"></line>
        <line x1="131.885" y1="151.659" x2="80.2846" y2="203.26" stroke="#26D7A0" className="svg-elem-9"></line>
        <path d="M183.067 151.703L140.706 142.715L131.719 100.354L174.08 109.342L183.067 151.703Z" stroke="#26D7A0" className="svg-elem-10"></path>
        <line x1="234.713" y1="203.26" x2="183.113" y2="151.659" stroke="#26D7A0" className="svg-elem-11"></line>
        <line x1="131.971" y1="100.52" x2="80.3705" y2="48.9199" stroke="#26D7A0" className="svg-elem-12"></line>
        <path d="M203.5 34V79.5H250.5" stroke="#26D7A0" className="svg-elem-13"></path>
        <path d="M111 218.5L111 173L64 173" stroke="#26D7A0" className="svg-elem-14"></path>
        <path d="M249.5 172.5L204 172.5L204 219.5" stroke="#26D7A0" className="svg-elem-15"></path>
        <path d="M65 80L110.5 80L110.5 33" stroke="#26D7A0" className="svg-elem-16"></path>
        <path d="M189.779 224.184L157.606 192.011L124.372 225.245" stroke="#26D7A0" className="svg-elem-17"></path>
        <path d="M124.725 28.3157L156.898 60.489L190.132 27.255" stroke="#26D7A0" className="svg-elem-18"></path>
        <path d="M59.3164 158.777L91.4898 126.603L58.2557 93.3695" stroke="#26D7A0" className="svg-elem-19"></path>
        <path d="M255.184 93.7229L223.01 125.896L256.244 159.13" stroke="#26D7A0" className="svg-elem-20"></path>
      </svg>
    </>
  )
}

export default HighCardinality
