/* eslint-disable max-len */
import * as React from "react"

const MetricStorage = () => {
  return (
    <>
      <style>
        {`
        /***************************************************
         * Generated by SVG Artista on 9/10/2022, 7:26:42 PM
         * MIT license (https://opensource.org/licenses/MIT)
         * W. https://svgartista.net
         **************************************************/
        
        svg .svg-elem-1 {
          stroke-dashoffset: 43.71209716796875px;
          stroke-dasharray: 43.71209716796875px;
          -webkit-transition: stroke-dashoffset 2s ease 0s;
                  transition: stroke-dashoffset 2s ease 0s;
        }
        
        svg.active .svg-elem-1 {
          stroke-dashoffset: 0;
        }
        
        svg .svg-elem-2 {
          stroke-dashoffset: 43.71209716796875px;
          stroke-dasharray: 43.71209716796875px;
          -webkit-transition: stroke-dashoffset 2s ease 0.12s;
                  transition: stroke-dashoffset 2s ease 0.12s;
        }
        
        svg.active .svg-elem-2 {
          stroke-dashoffset: 0;
        }
        
        svg .svg-elem-3 {
          stroke-dashoffset: 221.1444091796875px;
          stroke-dasharray: 221.1444091796875px;
          -webkit-transition: stroke-dashoffset 2s ease 0.24s;
                  transition: stroke-dashoffset 2s ease 0.24s;
        }
        
        svg.active .svg-elem-3 {
          stroke-dashoffset: 0;
        }
        
        svg .svg-elem-4 {
          stroke-dashoffset: 221.1444854736328px;
          stroke-dasharray: 221.1444854736328px;
          -webkit-transition: stroke-dashoffset 2s ease 0.36s;
                  transition: stroke-dashoffset 2s ease 0.36s;
        }
        
        svg.active .svg-elem-4 {
          stroke-dashoffset: 0;
        }
        
        svg .svg-elem-5 {
          stroke-dashoffset: 43.7118034362793px;
          stroke-dasharray: 43.7118034362793px;
          -webkit-transition: stroke-dashoffset 2s ease 0.48s;
                  transition: stroke-dashoffset 2s ease 0.48s;
        }
        
        svg.active .svg-elem-5 {
          stroke-dashoffset: 0;
        }
        
        svg .svg-elem-6 {
          stroke-dashoffset: 43.71179962158203px;
          stroke-dasharray: 43.71179962158203px;
          -webkit-transition: stroke-dashoffset 2s ease 0.6s;
                  transition: stroke-dashoffset 2s ease 0.6s;
        }
        
        svg.active .svg-elem-6 {
          stroke-dashoffset: 0;
        }
        
        svg .svg-elem-7 {
          stroke-dashoffset: 43.7118034362793px;
          stroke-dasharray: 43.7118034362793px;
          -webkit-transition: stroke-dashoffset 2s ease 0.72s;
                  transition: stroke-dashoffset 2s ease 0.72s;
        }
        
        svg.active .svg-elem-7 {
          stroke-dashoffset: 0;
        }
        
        svg .svg-elem-8 {
          stroke-dashoffset: 221.14443969726562px;
          stroke-dasharray: 221.14443969726562px;
          -webkit-transition: stroke-dashoffset 2s ease 0.84s;
                  transition: stroke-dashoffset 2s ease 0.84s;
        }
        
        svg.active .svg-elem-8 {
          stroke-dashoffset: 0;
        }
        
        svg .svg-elem-9 {
          stroke-dashoffset: 221.14447021484375px;
          stroke-dasharray: 221.14447021484375px;
          -webkit-transition: stroke-dashoffset 2s ease 0.96s;
                  transition: stroke-dashoffset 2s ease 0.96s;
        }
        
        svg.active .svg-elem-9 {
          stroke-dashoffset: 0;
        }
        
        svg .svg-elem-10 {
          stroke-dashoffset: 85.01530456542969px;
          stroke-dasharray: 85.01530456542969px;
          -webkit-transition: stroke-dashoffset 2s ease 1.08s;
                  transition: stroke-dashoffset 2s ease 1.08s;
        }
        
        svg.active .svg-elem-10 {
          stroke-dashoffset: 0;
        }
        
        svg .svg-elem-11 {
          stroke-dashoffset: 27.46929931640625px;
          stroke-dasharray: 27.46929931640625px;
          -webkit-transition: stroke-dashoffset 2s ease 1.2s;
                  transition: stroke-dashoffset 2s ease 1.2s;
        }
        
        svg.active .svg-elem-11 {
          stroke-dashoffset: 0;
        }
        
        svg .svg-elem-12 {
          stroke-dashoffset: 27.46900177001953px;
          stroke-dasharray: 27.46900177001953px;
          -webkit-transition: stroke-dashoffset 2s ease 1.3199999999999998s;
                  transition: stroke-dashoffset 2s ease 1.3199999999999998s;
        }
        
        svg.active .svg-elem-12 {
          stroke-dashoffset: 0;
        }
        
        svg .svg-elem-13 {
          stroke-dashoffset: 27.46929931640625px;
          stroke-dasharray: 27.46929931640625px;
          -webkit-transition: stroke-dashoffset 2s ease 1.44s;
                  transition: stroke-dashoffset 2s ease 1.44s;
        }
        
        svg.active .svg-elem-13 {
          stroke-dashoffset: 0;
        }
        
        svg .svg-elem-14 {
          stroke-dashoffset: 135.8107147216797px;
          stroke-dasharray: 135.8107147216797px;
          -webkit-transition: stroke-dashoffset 2s ease 1.56s;
                  transition: stroke-dashoffset 2s ease 1.56s;
        }
        
        svg.active .svg-elem-14 {
          stroke-dashoffset: 0;
        }
        
        svg .svg-elem-15 {
          stroke-dashoffset: 135.8104248046875px;
          stroke-dasharray: 135.8104248046875px;
          -webkit-transition: stroke-dashoffset 2s ease 1.68s;
                  transition: stroke-dashoffset 2s ease 1.68s;
        }
        
        svg.active .svg-elem-15 {
          stroke-dashoffset: 0;
        }
        
        svg .svg-elem-16 {
          stroke-dashoffset: 28.77899932861328px;
          stroke-dasharray: 28.77899932861328px;
          -webkit-transition: stroke-dashoffset 2s ease 1.7999999999999998s;
                  transition: stroke-dashoffset 2s ease 1.7999999999999998s;
        }
        
        svg.active .svg-elem-16 {
          stroke-dashoffset: 0;
        }
        
        svg .svg-elem-17 {
          stroke-dashoffset: 18.20800018310547px;
          stroke-dasharray: 18.20800018310547px;
          -webkit-transition: stroke-dashoffset 2s ease 1.92s;
                  transition: stroke-dashoffset 2s ease 1.92s;
        }
        
        svg.active .svg-elem-17 {
          stroke-dashoffset: 0;
        }
        
        svg .svg-elem-18 {
          stroke-dashoffset: 18.20800018310547px;
          stroke-dasharray: 18.20800018310547px;
          -webkit-transition: stroke-dashoffset 2s ease 2.04s;
                  transition: stroke-dashoffset 2s ease 2.04s;
        }
        
        svg.active .svg-elem-18 {
          stroke-dashoffset: 0;
        }
        
        svg .svg-elem-19 {
          stroke-dashoffset: 18.20800018310547px;
          stroke-dasharray: 18.20800018310547px;
          -webkit-transition: stroke-dashoffset 2s ease 2.16s;
                  transition: stroke-dashoffset 2s ease 2.16s;
        }
        
        svg.active .svg-elem-19 {
          stroke-dashoffset: 0;
        }
        
        svg .svg-elem-20 {
          stroke-dashoffset: 87.15107727050781px;
          stroke-dasharray: 87.15107727050781px;
          -webkit-transition: stroke-dashoffset 2s ease 2.28s;
                  transition: stroke-dashoffset 2s ease 2.28s;
        }
        
        svg.active .svg-elem-20 {
          stroke-dashoffset: 0;
        }
        
        svg .svg-elem-21 {
          stroke-dashoffset: 87.1513442993164px;
          stroke-dasharray: 87.1513442993164px;
          -webkit-transition: stroke-dashoffset 2s ease 2.4s;
                  transition: stroke-dashoffset 2s ease 2.4s;
        }
        
        svg.active .svg-elem-21 {
          stroke-dashoffset: 0;
        }
        
        svg .svg-elem-22 {
          stroke-dashoffset: 19.041000366210938px;
          stroke-dasharray: 19.041000366210938px;
          -webkit-transition: stroke-dashoffset 2s ease 2.52s;
                  transition: stroke-dashoffset 2s ease 2.52s;
        }
        
        svg.active .svg-elem-22 {
          stroke-dashoffset: 0;
        }
        


`}
      </style>
      <svg width="200" height="120" viewBox="0 0 229 140" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M1 111.629V69.9169" stroke="#0EFF51" className="svg-elem-1"></path>
        <path d="M95.7012 111.629V69.9169" stroke="#0EFF51" className="svg-elem-2"></path>
        <path d="M47.1075 138.347L1.79053 112.179C1.01409 111.728 1.10852 110.951 2.01087 110.437L46.8977 84.5208C47.7896 84.0067 49.1431 83.9437 49.9195 84.3949L95.247 110.563C96.0235 111.014 95.929 111.791 95.0267 112.305L50.1399 138.221C49.248 138.735 47.8945 138.798 47.118 138.347H47.1075Z" stroke="#0EFF51" strokeMiterlimit="10" className="svg-elem-3"></path>
        <path d="M47.1075 96.8886L1.79053 70.7204C1.01409 70.2692 1.10852 69.4927 2.01087 68.9786L46.8977 43.0622C47.7896 42.5481 49.1431 42.4851 49.9195 42.9363L95.247 69.1045C96.0235 69.5557 95.929 70.3321 95.0267 70.8463L50.1399 96.7627C49.248 97.2768 47.8945 97.3398 47.118 96.8886H47.1075Z" fill="#0A1725" stroke="#0EFF51" strokeMiterlimit="10" className="svg-elem-4"></path>
        <path d="M1.31543 69.995V28.2832" stroke="#26D7A0" className="svg-elem-5"></path>
        <path d="M48.7979 97.2782V55.5664" stroke="#26D7A0" className="svg-elem-6"></path>
        <path d="M96.0166 69.995V28.2832" stroke="#26D7A0" className="svg-elem-7"></path>
        <path d="M47.42 96.7134L2.10303 70.5452C1.32659 70.094 1.42102 69.3176 2.32337 68.8034L47.2102 42.887C48.1021 42.3729 49.4556 42.3099 50.232 42.7611L95.5595 68.9294C96.336 69.3805 96.2415 70.157 95.3392 70.6711L50.4524 96.5875C49.5605 97.1016 48.207 97.1646 47.4305 96.7134H47.42Z" fill="#0A1725" stroke="#6361D1" strokeMiterlimit="10" className="svg-elem-8"></path>
        <path d="M47.42 55.2548L2.10303 29.0866C1.32659 28.6354 1.42102 27.859 2.32337 27.3448L47.2102 1.4284C48.1021 0.914271 49.4556 0.851316 50.232 1.30249L95.5595 27.4707C96.336 27.9219 96.2415 28.6984 95.3392 29.2125L50.4524 55.1289C49.5605 55.643 48.207 55.706 47.4305 55.2548H47.42Z" fill="#0A1725" stroke="#26D7A0" strokeMiterlimit="10" className="svg-elem-9"></path>
        <path d="M48.9658 138.466L48.9658 55.4507" stroke="#26D7A0" className="svg-elem-10"></path>
        <path d="M112.341 110.076V84.6067" stroke="#26D7A0" className="svg-elem-11"></path>
        <path d="M141.333 126.735V101.266" stroke="#26D7A0" className="svg-elem-12"></path>
        <path d="M170.167 110.076V84.6067" stroke="#26D7A0" className="svg-elem-13"></path>
        <path d="M140.492 126.39L112.821 110.412C112.347 110.136 112.405 109.662 112.956 109.348L140.364 93.5237C140.909 93.2097 141.735 93.1713 142.209 93.4468L169.886 109.425C170.36 109.701 170.303 110.175 169.752 110.489L142.344 126.313C141.799 126.627 140.973 126.666 140.499 126.39H140.492Z" fill="#0A1725" stroke="#26D7A0" strokeMiterlimit="10" className="svg-elem-14"></path>
        <path d="M140.492 101.075L112.821 85.0971C112.347 84.8216 112.405 84.3475 112.956 84.0336L140.364 68.209C140.909 67.895 141.735 67.8566 142.209 68.1321L169.886 84.1104C170.36 84.3859 170.303 84.86 169.752 85.174L142.344 100.999C141.799 101.312 140.973 101.351 140.499 101.075H140.492Z" fill="#0A1725" stroke="#26D7A0" strokeMiterlimit="10" className="svg-elem-15"></path>
        <path d="M141.799 126.861L141.799 100.082" stroke="#26D7A0" className="svg-elem-16"></path>
        <path d="M191.598 116.18V99.972" stroke="#26D7A0" className="svg-elem-17"></path>
        <path d="M210.046 126.781V110.573" stroke="#26D7A0" className="svg-elem-18"></path>
        <path d="M228.394 116.18V99.972" stroke="#26D7A0" className="svg-elem-19"></path>
        <path d="M209.511 126.561L191.902 116.393C191.601 116.218 191.637 115.916 191.988 115.717L209.429 105.646C209.776 105.447 210.302 105.422 210.603 105.598L228.216 115.766C228.518 115.941 228.481 116.243 228.13 116.442L210.689 126.513C210.342 126.712 209.817 126.737 209.515 126.561H209.511Z" fill="#0A1725" stroke="#26D7A0" strokeMiterlimit="10" className="svg-elem-20"></path>
        <path d="M209.511 110.452L191.902 100.284C191.601 100.109 191.637 99.807 191.988 99.6073L209.429 89.5371C209.776 89.3373 210.302 89.3128 210.603 89.4881L228.216 99.6562C228.518 99.8315 228.481 100.133 228.13 100.333L210.689 110.403C210.342 110.603 209.817 110.627 209.515 110.452H209.511Z" fill="#0A1725" stroke="#26D7A0" strokeMiterlimit="10" className="svg-elem-21"></path>
        <path d="M210.343 126.861L210.343 109.82" stroke="#26D7A0" className="svg-elem-22"></path>
      </svg>

    </>
  )
}

export default MetricStorage
