/* eslint-disable max-len */
import * as React from "react"

const OperationalTail = () => {
  return (
    <>
      <style>
        {`
       /***************************************************
        * Generated by SVG Artista on 9/10/2022, 7:58:37 PM
        * MIT license (https://opensource.org/licenses/MIT)
        * W. https://svgartista.net
        **************************************************/
       
       @-webkit-keyframes animate-svg-stroke-1 {
         0% {
           stroke-dashoffset: 868px;
           stroke-dasharray: 868px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 868px;
         }
       }
       
       @keyframes animate-svg-stroke-1 {
         0% {
           stroke-dashoffset: 868px;
           stroke-dasharray: 868px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 868px;
         }
       }
       
       .svg-elem-1 {
         -webkit-animation: animate-svg-stroke-1 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0s both,
                              animate-svg-fill-1 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s both;
                 animation: animate-svg-stroke-1 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0s both,
                      animate-svg-fill-1 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s both;
       }
       
       @-webkit-keyframes animate-svg-stroke-2 {
         0% {
           stroke-dashoffset: 640px;
           stroke-dasharray: 640px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 640px;
         }
       }
       
       @keyframes animate-svg-stroke-2 {
         0% {
           stroke-dashoffset: 640px;
           stroke-dasharray: 640px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 640px;
         }
       }
       
       .svg-elem-2 {
         -webkit-animation: animate-svg-stroke-2 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s both,
                              animate-svg-fill-2 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s both;
                 animation: animate-svg-stroke-2 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s both,
                      animate-svg-fill-2 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s both;
       }
       
       @-webkit-keyframes animate-svg-stroke-3 {
         0% {
           stroke-dashoffset: 692px;
           stroke-dasharray: 692px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 692px;
         }
       }
       
       @keyframes animate-svg-stroke-3 {
         0% {
           stroke-dashoffset: 692px;
           stroke-dasharray: 692px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 692px;
         }
       }
       
       .svg-elem-3 {
         -webkit-animation: animate-svg-stroke-3 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s both,
                              animate-svg-fill-3 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s both;
                 animation: animate-svg-stroke-3 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s both,
                      animate-svg-fill-3 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s both;
       }
       
       @-webkit-keyframes animate-svg-stroke-4 {
         0% {
           stroke-dashoffset: 237px;
           stroke-dasharray: 237px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 237px;
         }
       }
       
       @keyframes animate-svg-stroke-4 {
         0% {
           stroke-dashoffset: 237px;
           stroke-dasharray: 237px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 237px;
         }
       }
       
       .svg-elem-4 {
         -webkit-animation: animate-svg-stroke-4 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s both,
                              animate-svg-fill-4 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s both;
                 animation: animate-svg-stroke-4 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s both,
                      animate-svg-fill-4 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s both;
       }
       
       @-webkit-keyframes animate-svg-stroke-5 {
         0% {
           stroke-dashoffset: 8.283185307179586px;
           stroke-dasharray: 8.283185307179586px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 8.283185307179586px;
         }
       }
       
       @keyframes animate-svg-stroke-5 {
         0% {
           stroke-dashoffset: 8.283185307179586px;
           stroke-dasharray: 8.283185307179586px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 8.283185307179586px;
         }
       }
       
       @-webkit-keyframes animate-svg-fill-5 {
         0% {
           fill: transparent;
         }
       
         100% {
           fill: rgb(10, 23, 37);
         }
       }
       
       @keyframes animate-svg-fill-5 {
         0% {
           fill: transparent;
         }
       
         100% {
           fill: rgb(10, 23, 37);
         }
       }
       
       .svg-elem-5 {
         -webkit-animation: animate-svg-stroke-5 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.48s both,
                              animate-svg-fill-5 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2000000000000002s both;
                 animation: animate-svg-stroke-5 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.48s both,
                      animate-svg-fill-5 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2000000000000002s both;
       }
       
       @-webkit-keyframes animate-svg-stroke-6 {
         0% {
           stroke-dashoffset: 8.283185307179586px;
           stroke-dasharray: 8.283185307179586px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 8.283185307179586px;
         }
       }
       
       @keyframes animate-svg-stroke-6 {
         0% {
           stroke-dashoffset: 8.283185307179586px;
           stroke-dasharray: 8.283185307179586px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 8.283185307179586px;
         }
       }
       
       @-webkit-keyframes animate-svg-fill-6 {
         0% {
           fill: transparent;
         }
       
         100% {
           fill: rgb(10, 23, 37);
         }
       }
       
       @keyframes animate-svg-fill-6 {
         0% {
           fill: transparent;
         }
       
         100% {
           fill: rgb(10, 23, 37);
         }
       }
       
       .svg-elem-6 {
         -webkit-animation: animate-svg-stroke-6 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.6s both,
                              animate-svg-fill-6 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3s both;
                 animation: animate-svg-stroke-6 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.6s both,
                      animate-svg-fill-6 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3s both;
       }
       
       @-webkit-keyframes animate-svg-stroke-7 {
         0% {
           stroke-dashoffset: 8.283185307179586px;
           stroke-dasharray: 8.283185307179586px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 8.283185307179586px;
         }
       }
       
       @keyframes animate-svg-stroke-7 {
         0% {
           stroke-dashoffset: 8.283185307179586px;
           stroke-dasharray: 8.283185307179586px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 8.283185307179586px;
         }
       }
       
       @-webkit-keyframes animate-svg-fill-7 {
         0% {
           fill: transparent;
         }
       
         100% {
           fill: rgb(10, 23, 37);
         }
       }
       
       @keyframes animate-svg-fill-7 {
         0% {
           fill: transparent;
         }
       
         100% {
           fill: rgb(10, 23, 37);
         }
       }
       
       .svg-elem-7 {
         -webkit-animation: animate-svg-stroke-7 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.72s both,
                              animate-svg-fill-7 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4000000000000001s both;
                 animation: animate-svg-stroke-7 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.72s both,
                      animate-svg-fill-7 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4000000000000001s both;
       }
       
       @-webkit-keyframes animate-svg-stroke-8 {
         0% {
           stroke-dashoffset: 206px;
           stroke-dasharray: 206px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 206px;
         }
       }
       
       @keyframes animate-svg-stroke-8 {
         0% {
           stroke-dashoffset: 206px;
           stroke-dasharray: 206px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 206px;
         }
       }
       
       .svg-elem-8 {
         -webkit-animation: animate-svg-stroke-8 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.84s both,
                              animate-svg-fill-8 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.5s both;
                 animation: animate-svg-stroke-8 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.84s both,
                      animate-svg-fill-8 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.5s both;
       }
       
       @-webkit-keyframes animate-svg-stroke-9 {
         0% {
           stroke-dashoffset: 206px;
           stroke-dasharray: 206px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 206px;
         }
       }
       
       @keyframes animate-svg-stroke-9 {
         0% {
           stroke-dashoffset: 206px;
           stroke-dasharray: 206px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 206px;
         }
       }
       
       .svg-elem-9 {
         -webkit-animation: animate-svg-stroke-9 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.96s both,
                              animate-svg-fill-9 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6s both;
                 animation: animate-svg-stroke-9 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.96s both,
                      animate-svg-fill-9 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6s both;
       }
       
       @-webkit-keyframes animate-svg-stroke-10 {
         0% {
           stroke-dashoffset: 206px;
           stroke-dasharray: 206px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 206px;
         }
       }
       
       @keyframes animate-svg-stroke-10 {
         0% {
           stroke-dashoffset: 206px;
           stroke-dasharray: 206px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 206px;
         }
       }
       
       .svg-elem-10 {
         -webkit-animation: animate-svg-stroke-10 2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.08s both,
                              animate-svg-fill-10 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.7000000000000002s both;
                 animation: animate-svg-stroke-10 2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.08s both,
                      animate-svg-fill-10 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.7000000000000002s both;
       }
       
       @-webkit-keyframes animate-svg-stroke-11 {
         0% {
           stroke-dashoffset: 206px;
           stroke-dasharray: 206px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 206px;
         }
       }
       
       @keyframes animate-svg-stroke-11 {
         0% {
           stroke-dashoffset: 206px;
           stroke-dasharray: 206px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 206px;
         }
       }
       
       .svg-elem-11 {
         -webkit-animation: animate-svg-stroke-11 2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2s both,
                              animate-svg-fill-11 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.8s both;
                 animation: animate-svg-stroke-11 2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2s both,
                      animate-svg-fill-11 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.8s both;
       }
       
       @-webkit-keyframes animate-svg-stroke-12 {
         0% {
           stroke-dashoffset: 206px;
           stroke-dasharray: 206px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 206px;
         }
       }
       
       @keyframes animate-svg-stroke-12 {
         0% {
           stroke-dashoffset: 206px;
           stroke-dasharray: 206px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 206px;
         }
       }
       
       .svg-elem-12 {
         -webkit-animation: animate-svg-stroke-12 2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3199999999999998s both,
                              animate-svg-fill-12 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.9000000000000001s both;
                 animation: animate-svg-stroke-12 2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3199999999999998s both,
                      animate-svg-fill-12 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.9000000000000001s both;
       }
       
       @-webkit-keyframes animate-svg-stroke-13 {
         0% {
           stroke-dashoffset: 36px;
           stroke-dasharray: 36px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 36px;
         }
       }
       
       @keyframes animate-svg-stroke-13 {
         0% {
           stroke-dashoffset: 36px;
           stroke-dasharray: 36px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 36px;
         }
       }
       
       .svg-elem-13 {
         -webkit-animation: animate-svg-stroke-13 2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.44s both,
                              animate-svg-fill-13 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2s both;
                 animation: animate-svg-stroke-13 2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.44s both,
                      animate-svg-fill-13 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2s both;
       }
       
       @-webkit-keyframes animate-svg-stroke-14 {
         0% {
           stroke-dashoffset: 36px;
           stroke-dasharray: 36px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 36px;
         }
       }
       
       @keyframes animate-svg-stroke-14 {
         0% {
           stroke-dashoffset: 36px;
           stroke-dasharray: 36px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 36px;
         }
       }
       
       .svg-elem-14 {
         -webkit-animation: animate-svg-stroke-14 2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.56s both,
                              animate-svg-fill-14 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.1s both;
                 animation: animate-svg-stroke-14 2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.56s both,
                      animate-svg-fill-14 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.1s both;
       }
       
       @-webkit-keyframes animate-svg-stroke-15 {
         0% {
           stroke-dashoffset: 36px;
           stroke-dasharray: 36px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 36px;
         }
       }
       
       @keyframes animate-svg-stroke-15 {
         0% {
           stroke-dashoffset: 36px;
           stroke-dasharray: 36px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 36px;
         }
       }
       
       .svg-elem-15 {
         -webkit-animation: animate-svg-stroke-15 2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.68s both,
                              animate-svg-fill-15 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.2s both;
                 animation: animate-svg-stroke-15 2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.68s both,
                      animate-svg-fill-15 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.2s both;
       }
       
       @-webkit-keyframes animate-svg-stroke-16 {
         0% {
           stroke-dashoffset: 36px;
           stroke-dasharray: 36px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 36px;
         }
       }
       
       @keyframes animate-svg-stroke-16 {
         0% {
           stroke-dashoffset: 36px;
           stroke-dasharray: 36px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 36px;
         }
       }
       
       .svg-elem-16 {
         -webkit-animation: animate-svg-stroke-16 2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.7999999999999998s both,
                              animate-svg-fill-16 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.3s both;
                 animation: animate-svg-stroke-16 2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.7999999999999998s both,
                      animate-svg-fill-16 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.3s both;
       }
       
       @-webkit-keyframes animate-svg-stroke-17 {
         0% {
           stroke-dashoffset: 36px;
           stroke-dasharray: 36px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 36px;
         }
       }
       
       @keyframes animate-svg-stroke-17 {
         0% {
           stroke-dashoffset: 36px;
           stroke-dasharray: 36px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 36px;
         }
       }
       
       .svg-elem-17 {
         -webkit-animation: animate-svg-stroke-17 2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.92s both,
                              animate-svg-fill-17 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.4000000000000004s both;
                 animation: animate-svg-stroke-17 2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.92s both,
                      animate-svg-fill-17 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.4000000000000004s both;
       }
       
       @-webkit-keyframes animate-svg-stroke-18 {
         0% {
           stroke-dashoffset: 36px;
           stroke-dasharray: 36px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 36px;
         }
       }
       
       @keyframes animate-svg-stroke-18 {
         0% {
           stroke-dashoffset: 36px;
           stroke-dasharray: 36px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 36px;
         }
       }
       
       .svg-elem-18 {
         -webkit-animation: animate-svg-stroke-18 2s cubic-bezier(0.47, 0, 0.745, 0.715) 2.04s both,
                              animate-svg-fill-18 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.5s both;
                 animation: animate-svg-stroke-18 2s cubic-bezier(0.47, 0, 0.745, 0.715) 2.04s both,
                      animate-svg-fill-18 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.5s both;
       }
       
       @-webkit-keyframes animate-svg-stroke-19 {
         0% {
           stroke-dashoffset: 36px;
           stroke-dasharray: 36px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 36px;
         }
       }
       
       @keyframes animate-svg-stroke-19 {
         0% {
           stroke-dashoffset: 36px;
           stroke-dasharray: 36px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 36px;
         }
       }
       
       .svg-elem-19 {
         -webkit-animation: animate-svg-stroke-19 2s cubic-bezier(0.47, 0, 0.745, 0.715) 2.16s both,
                              animate-svg-fill-19 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.6s both;
                 animation: animate-svg-stroke-19 2s cubic-bezier(0.47, 0, 0.745, 0.715) 2.16s both,
                      animate-svg-fill-19 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.6s both;
       }
       
       @-webkit-keyframes animate-svg-stroke-20 {
         0% {
           stroke-dashoffset: 36px;
           stroke-dasharray: 36px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 36px;
         }
       }
       
       @keyframes animate-svg-stroke-20 {
         0% {
           stroke-dashoffset: 36px;
           stroke-dasharray: 36px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 36px;
         }
       }
       
       .svg-elem-20 {
         -webkit-animation: animate-svg-stroke-20 2s cubic-bezier(0.47, 0, 0.745, 0.715) 2.28s both,
                              animate-svg-fill-20 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.7s both;
                 animation: animate-svg-stroke-20 2s cubic-bezier(0.47, 0, 0.745, 0.715) 2.28s both,
                      animate-svg-fill-20 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.7s both;
       }
       
       @-webkit-keyframes animate-svg-stroke-21 {
         0% {
           stroke-dashoffset: 36px;
           stroke-dasharray: 36px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 36px;
         }
       }
       
       @keyframes animate-svg-stroke-21 {
         0% {
           stroke-dashoffset: 36px;
           stroke-dasharray: 36px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 36px;
         }
       }
       
       .svg-elem-21 {
         -webkit-animation: animate-svg-stroke-21 2s cubic-bezier(0.47, 0, 0.745, 0.715) 2.4s both,
                              animate-svg-fill-21 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.8s both;
                 animation: animate-svg-stroke-21 2s cubic-bezier(0.47, 0, 0.745, 0.715) 2.4s both,
                      animate-svg-fill-21 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.8s both;
       }
       
       @-webkit-keyframes animate-svg-stroke-22 {
         0% {
           stroke-dashoffset: 36px;
           stroke-dasharray: 36px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 36px;
         }
       }
       
       @keyframes animate-svg-stroke-22 {
         0% {
           stroke-dashoffset: 36px;
           stroke-dasharray: 36px;
         }
       
         100% {
           stroke-dashoffset: 0;
           stroke-dasharray: 36px;
         }
       }
       
       .svg-elem-22 {
         -webkit-animation: animate-svg-stroke-22 2s cubic-bezier(0.47, 0, 0.745, 0.715) 2.52s both,
                              animate-svg-fill-22 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.9000000000000004s both;
                 animation: animate-svg-stroke-22 2s cubic-bezier(0.47, 0, 0.745, 0.715) 2.52s both,
                      animate-svg-fill-22 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.9000000000000004s both;
       }
       
        


`}
      </style>
      <svg
        width="200"
        height="100"
        viewBox="0 0 316 159"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <rect
          x="18.5"
          y="0.5"
          width="279"
          height="154"
          stroke="#43DCA5"
          className="svg-elem-1"
        ></rect>
        <rect
          x="0.5"
          y="-0.5"
          width="315"
          height="4"
          transform="matrix(1 0 0 -1 0 158)"
          stroke="#43DCA5"
          className="svg-elem-2"
        ></rect>
        <rect
          x="40.5"
          y="22.5"
          width="236"
          height="109"
          stroke="#0A1725"
          className="svg-elem-3"
        ></rect>
        <line
          x1="40"
          y1="31.5"
          x2="275"
          y2="31.5"
          stroke="#0A1725"
          className="svg-elem-4"
        ></line>
        <circle
          cx="46"
          cy="27"
          r="1"
          fill="#0A1725"
          className="svg-elem-5"
        ></circle>
        <circle
          cx="51"
          cy="27"
          r="1"
          fill="#0A1725"
          className="svg-elem-6"
        ></circle>
        <circle
          cx="55"
          cy="27"
          r="1"
          fill="#0A1725"
          className="svg-elem-7"
        ></circle>
        <rect
          x="56.5"
          y="47.5"
          width="34"
          height="68"
          stroke="#43DCA5"
          className="svg-elem-8"
        ></rect>
        <rect
          x="97.5"
          y="47.5"
          width="34"
          height="68"
          stroke="#43DCA5"
          className="svg-elem-9"
        ></rect>
        <rect
          x="138.5"
          y="47.5"
          width="34"
          height="68"
          stroke="#43DCA5"
          className="svg-elem-10"
        ></rect>
        <rect
          x="179.5"
          y="47.5"
          width="34"
          height="68"
          stroke="#43DCA5"
          className="svg-elem-11"
        ></rect>
        <rect
          x="220.5"
          y="47.5"
          width="34"
          height="68"
          stroke="#43DCA5"
          className="svg-elem-12"
        ></rect>
        <line
          x1="56"
          y1="101.5"
          x2="90"
          y2="101.5"
          stroke="#43DCA5"
          className="svg-elem-13"
        ></line>
        <line
          x1="98"
          y1="101.5"
          x2="132"
          y2="101.5"
          stroke="#43DCA5"
          className="svg-elem-14"
        ></line>
        <line
          x1="138"
          y1="101.5"
          x2="172"
          y2="101.5"
          stroke="#43DCA5"
          className="svg-elem-15"
        ></line>
        <line
          x1="179"
          y1="101.5"
          x2="213"
          y2="101.5"
          stroke="#43DCA5"
          className="svg-elem-16"
        ></line>
        <line
          x1="220"
          y1="101.5"
          x2="254"
          y2="101.5"
          stroke="#43DCA5"
          className="svg-elem-17"
        ></line>
        <line
          x1="56"
          y1="88.5"
          x2="90"
          y2="88.5"
          stroke="#43DCA5"
          className="svg-elem-18"
        ></line>
        <line
          x1="138"
          y1="88.5"
          x2="172"
          y2="88.5"
          stroke="#43DCA5"
          className="svg-elem-19"
        ></line>
        <line
          x1="179"
          y1="88.5"
          x2="213"
          y2="88.5"
          stroke="#43DCA5"
          className="svg-elem-20"
        ></line>
        <line
          x1="98"
          y1="88.5"
          x2="132"
          y2="88.5"
          stroke="#43DCA5"
          className="svg-elem-21"
        ></line>
        <line
          x1="220"
          y1="88.5"
          x2="254"
          y2="88.5"
          stroke="#43DCA5"
          className="svg-elem-22"
        ></line>
      </svg>
    </>
  )
}

export default OperationalTail
