/* eslint-disable max-len */
import * as React from "react"

const ChangeIntelligence = () => {
  return (
    <>
      <style>
        {`
        /***************************************************
         * Generated by SVG Artista on 9/10/2022, 8:45:25 PM
         * MIT license (https://opensource.org/licenses/MIT)
         * W. https://svgartista.net
         **************************************************/
        
        @-webkit-keyframes animate-svg-stroke-1 {
          0% {
            stroke-dashoffset: 33.41592653589793px;
            stroke-dasharray: 33.41592653589793px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 33.41592653589793px;
          }
        }
        
        @keyframes animate-svg-stroke-1 {
          0% {
            stroke-dashoffset: 33.41592653589793px;
            stroke-dasharray: 33.41592653589793px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 33.41592653589793px;
          }
        }
        
        .svg-elem-1 {
          -webkit-animation: animate-svg-stroke-1 2s linear 0s both;
                  animation: animate-svg-stroke-1 2s linear 0s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-2 {
          0% {
            stroke-dashoffset: 248.06500244140625px;
            stroke-dasharray: 248.06500244140625px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 248.06500244140625px;
          }
        }
        
        @keyframes animate-svg-stroke-2 {
          0% {
            stroke-dashoffset: 248.06500244140625px;
            stroke-dasharray: 248.06500244140625px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 248.06500244140625px;
          }
        }
        
        .svg-elem-2 {
          -webkit-animation: animate-svg-stroke-2 2s linear 1s both;
                  animation: animate-svg-stroke-2 2s linear 1s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-3 {
          0% {
            stroke-dashoffset: 421.46282958984375px;
            stroke-dasharray: 421.46282958984375px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 421.46282958984375px;
          }
        }
        
        @keyframes animate-svg-stroke-3 {
          0% {
            stroke-dashoffset: 421.46282958984375px;
            stroke-dasharray: 421.46282958984375px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 421.46282958984375px;
          }
        }
        
        .svg-elem-3 {
          -webkit-animation: animate-svg-stroke-3 2s linear 2s both;
                  animation: animate-svg-stroke-3 2s linear 2s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-4 {
          0% {
            stroke-dashoffset: 105px;
            stroke-dasharray: 105px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 105px;
          }
        }
        
        @keyframes animate-svg-stroke-4 {
          0% {
            stroke-dashoffset: 105px;
            stroke-dasharray: 105px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 105px;
          }
        }
        
        .svg-elem-4 {
          -webkit-animation: animate-svg-stroke-4 2s linear 3s both;
                  animation: animate-svg-stroke-4 2s linear 3s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-5 {
          0% {
            stroke-dashoffset: 88px;
            stroke-dasharray: 88px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 88px;
          }
        }
        
        @keyframes animate-svg-stroke-5 {
          0% {
            stroke-dashoffset: 88px;
            stroke-dasharray: 88px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 88px;
          }
        }
        
        .svg-elem-5 {
          -webkit-animation: animate-svg-stroke-5 2s linear 4s both;
                  animation: animate-svg-stroke-5 2s linear 4s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-6 {
          0% {
            stroke-dashoffset: 129px;
            stroke-dasharray: 129px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 129px;
          }
        }
        
        @keyframes animate-svg-stroke-6 {
          0% {
            stroke-dashoffset: 129px;
            stroke-dasharray: 129px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 129px;
          }
        }
        
        .svg-elem-6 {
          -webkit-animation: animate-svg-stroke-6 2s linear 5s both;
                  animation: animate-svg-stroke-6 2s linear 5s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-7 {
          0% {
            stroke-dashoffset: 185.03024291992188px;
            stroke-dasharray: 185.03024291992188px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 185.03024291992188px;
          }
        }
        
        @keyframes animate-svg-stroke-7 {
          0% {
            stroke-dashoffset: 185.03024291992188px;
            stroke-dasharray: 185.03024291992188px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 185.03024291992188px;
          }
        }
        
        .svg-elem-7 {
          -webkit-animation: animate-svg-stroke-7 2s linear 6s both;
                  animation: animate-svg-stroke-7 2s linear 6s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-8 {
          0% {
            stroke-dashoffset: 86.236328125px;
            stroke-dasharray: 86.236328125px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 86.236328125px;
          }
        }
        
        @keyframes animate-svg-stroke-8 {
          0% {
            stroke-dashoffset: 86.236328125px;
            stroke-dasharray: 86.236328125px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 86.236328125px;
          }
        }
        
        .svg-elem-8 {
          -webkit-animation: animate-svg-stroke-8 2s linear 7s both;
                  animation: animate-svg-stroke-8 2s linear 7s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-9 {
          0% {
            stroke-dashoffset: 261.9593811035156px;
            stroke-dasharray: 261.9593811035156px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 261.9593811035156px;
          }
        }
        
        @keyframes animate-svg-stroke-9 {
          0% {
            stroke-dashoffset: 261.9593811035156px;
            stroke-dasharray: 261.9593811035156px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 261.9593811035156px;
          }
        }
        
        .svg-elem-9 {
          -webkit-animation: animate-svg-stroke-9 2s linear 8s both;
                  animation: animate-svg-stroke-9 2s linear 8s both;
        }
        
   
   
        
`}
      </style>
      <svg
        width="220"
        height="300"
        viewBox="0 0 220 300"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <circle
          cx="115.5"
          cy="5.5"
          r="5"
          stroke="#F85E60"
          className="svg-elem-1"
        ></circle>
        <path
          d="M219 20C219 36.6516 219 50.0259 219 54.6317C219 65.6146 211.983 86.2519 187.277 86.2519C158.41 86.2519 161.064 104.675 161.064 112.381C161.064 119.112 161.064 204.019 161.064 230"
          stroke="#26D7A0"
          className="svg-elem-2"
        ></path>
        <path
          d="M116.021 13V85.0417C116.021 97.7292 117.907 112.312 143.16 112.312C167.193 112.312 176.104 112.312 177.555 112.312C187.037 112.069 206 117.446 206 140.896C206 164.346 206 139.389 206 162.333C206 197.333 186.553 201.125 150.271 201.125C113.989 201.125 116.021 227.667 116.021 235.542C116.021 242.687 116.021 294.458 116.021 300"
          stroke="#F85E60"
          className=""
        ></path>
        {/* <path d="M116 88L116 191" stroke="#26D7A0" className="svg-elem-4"></path> */}
        <path d="M174 91L174 177" stroke="#26D7A0" className="svg-elem-5"></path>
        <path d="M148 112V239" stroke="#26D7A0" className="svg-elem-6"></path>
        <path
          d="M116 87H113.941C107.765 87 96 89.1541 96 104.757C96 120.36 96 232.063 96 257"
          stroke="#26D7A0"
          className="svg-elem-7"
        ></path>
        <path
          d="M146 112H141.35C137.282 112 129 113.087 129 124.49C129 135.892 129 168.914 129 184"
          stroke="#26D7A0"
          className="svg-elem-8"
        ></path>
        <path
          d="M1 13C1 40.4423 1 62.4837 1 70.0741C1.00005 88.1743 12.4941 122.185 52.9595 122.185C100.242 122.185 95.8952 152.547 95.8952 165.246C95.8952 176.34 95.8952 171.182 95.8952 214"
          stroke="#26D7A0"
          className="svg-elem-9"
        ></path>
      </svg>
    </>
  )
}

export default ChangeIntelligence
