/* eslint-disable max-len */
import * as React from "react"

const DeathDashboard = () => {

  return (
    <>
      <style>
        {`
        /***************************************************
         * Generated by SVG Artista on 9/10/2022, 8:15:48 PM
         * MIT license (https://opensource.org/licenses/MIT)
         * W. https://svgartista.net
         **************************************************/
        
        @-webkit-keyframes animate-svg-stroke-1 {
          0% {
            stroke-dashoffset: 798px;
            stroke-dasharray: 798px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 798px;
          }
        }
        
        @keyframes animate-svg-stroke-1 {
          0% {
            stroke-dashoffset: 798px;
            stroke-dasharray: 798px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 798px;
          }
        }
        
        .svg-elem-1 {
          -webkit-animation: animate-svg-stroke-1 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0s both,
                               animate-svg-fill-1 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s both;
                  animation: animate-svg-stroke-1 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0s both,
                       animate-svg-fill-1 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-2 {
          0% {
            stroke-dashoffset: 242px;
            stroke-dasharray: 242px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 242px;
          }
        }
        
        @keyframes animate-svg-stroke-2 {
          0% {
            stroke-dashoffset: 242px;
            stroke-dasharray: 242px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 242px;
          }
        }
        
        .svg-elem-2 {
          -webkit-animation: animate-svg-stroke-2 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s both,
                               animate-svg-fill-2 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s both;
                  animation: animate-svg-stroke-2 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s both,
                       animate-svg-fill-2 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-3 {
          0% {
            stroke-dashoffset: 8.36273043316848px;
            stroke-dasharray: 8.36273043316848px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 8.36273043316848px;
          }
        }
        
        @keyframes animate-svg-stroke-3 {
          0% {
            stroke-dashoffset: 8.36273043316848px;
            stroke-dasharray: 8.36273043316848px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 8.36273043316848px;
          }
        }
        
        @-webkit-keyframes animate-svg-fill-3 {
          0% {
            fill: transparent;
          }
        
          100% {
            fill: rgb(67, 220, 165);
          }
        }
        
        @keyframes animate-svg-fill-3 {
          0% {
            fill: transparent;
          }
        
          100% {
            fill: rgb(67, 220, 165);
          }
        }
        
        .svg-elem-3 {
          -webkit-animation: animate-svg-stroke-3 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s both,
                               animate-svg-fill-3 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s both;
                  animation: animate-svg-stroke-3 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s both,
                       animate-svg-fill-3 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-4 {
          0% {
            stroke-dashoffset: 8.36273043316848px;
            stroke-dasharray: 8.36273043316848px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 8.36273043316848px;
          }
        }
        
        @keyframes animate-svg-stroke-4 {
          0% {
            stroke-dashoffset: 8.36273043316848px;
            stroke-dasharray: 8.36273043316848px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 8.36273043316848px;
          }
        }
        
        @-webkit-keyframes animate-svg-fill-4 {
          0% {
            fill: transparent;
          }
        
          100% {
            fill: rgb(67, 220, 165);
          }
        }
        
        @keyframes animate-svg-fill-4 {
          0% {
            fill: transparent;
          }
        
          100% {
            fill: rgb(67, 220, 165);
          }
        }
        
        .svg-elem-4 {
          -webkit-animation: animate-svg-stroke-4 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s both,
                               animate-svg-fill-4 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s both;
                  animation: animate-svg-stroke-4 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s both,
                       animate-svg-fill-4 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-5 {
          0% {
            stroke-dashoffset: 8.36273043316848px;
            stroke-dasharray: 8.36273043316848px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 8.36273043316848px;
          }
        }
        
        @keyframes animate-svg-stroke-5 {
          0% {
            stroke-dashoffset: 8.36273043316848px;
            stroke-dasharray: 8.36273043316848px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 8.36273043316848px;
          }
        }
        
        @-webkit-keyframes animate-svg-fill-5 {
          0% {
            fill: transparent;
          }
        
          100% {
            fill: rgb(67, 220, 165);
          }
        }
        
        @keyframes animate-svg-fill-5 {
          0% {
            fill: transparent;
          }
        
          100% {
            fill: rgb(67, 220, 165);
          }
        }
        
        .svg-elem-5 {
          -webkit-animation: animate-svg-stroke-5 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.48s both,
                               animate-svg-fill-5 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2000000000000002s both;
                  animation: animate-svg-stroke-5 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.48s both,
                       animate-svg-fill-5 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2000000000000002s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-6 {
          0% {
            stroke-dashoffset: 243.68774938890854px;
            stroke-dasharray: 243.68774938890854px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 243.68774938890854px;
          }
        }
        
        @keyframes animate-svg-stroke-6 {
          0% {
            stroke-dashoffset: 243.68774938890854px;
            stroke-dasharray: 243.68774938890854px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 243.68774938890854px;
          }
        }
        
        .svg-elem-6 {
          -webkit-animation: animate-svg-stroke-6 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.6s both,
                               animate-svg-fill-6 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3s both;
                  animation: animate-svg-stroke-6 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.6s both,
                       animate-svg-fill-6 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-7 {
          0% {
            stroke-dashoffset: 41.863853454589844px;
            stroke-dasharray: 41.863853454589844px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 41.863853454589844px;
          }
        }
        
        @keyframes animate-svg-stroke-7 {
          0% {
            stroke-dashoffset: 41.863853454589844px;
            stroke-dasharray: 41.863853454589844px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 41.863853454589844px;
          }
        }
        
        .svg-elem-7 {
          -webkit-animation: animate-svg-stroke-7 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.72s both,
                               animate-svg-fill-7 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4000000000000001s both;
                  animation: animate-svg-stroke-7 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.72s both,
                       animate-svg-fill-7 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4000000000000001s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-8 {
          0% {
            stroke-dashoffset: 23.991148575128552px;
            stroke-dasharray: 23.991148575128552px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 23.991148575128552px;
          }
        }
        
        @keyframes animate-svg-stroke-8 {
          0% {
            stroke-dashoffset: 23.991148575128552px;
            stroke-dasharray: 23.991148575128552px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 23.991148575128552px;
          }
        }
        
        .svg-elem-8 {
          -webkit-animation: animate-svg-stroke-8 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.84s both,
                               animate-svg-fill-8 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.5s both;
                  animation: animate-svg-stroke-8 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.84s both,
                       animate-svg-fill-8 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.5s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-9 {
          0% {
            stroke-dashoffset: 23.991148575128552px;
            stroke-dasharray: 23.991148575128552px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 23.991148575128552px;
          }
        }
        
        @keyframes animate-svg-stroke-9 {
          0% {
            stroke-dashoffset: 23.991148575128552px;
            stroke-dasharray: 23.991148575128552px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 23.991148575128552px;
          }
        }
        
        .svg-elem-9 {
          -webkit-animation: animate-svg-stroke-9 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.96s both,
                               animate-svg-fill-9 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6s both;
                  animation: animate-svg-stroke-9 2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.96s both,
                       animate-svg-fill-9 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-10 {
          0% {
            stroke-dashoffset: 23.991148575128552px;
            stroke-dasharray: 23.991148575128552px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 23.991148575128552px;
          }
        }
        
        @keyframes animate-svg-stroke-10 {
          0% {
            stroke-dashoffset: 23.991148575128552px;
            stroke-dasharray: 23.991148575128552px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 23.991148575128552px;
          }
        }
        
        .svg-elem-10 {
          -webkit-animation: animate-svg-stroke-10 2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.08s both,
                               animate-svg-fill-10 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.7000000000000002s both;
                  animation: animate-svg-stroke-10 2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.08s both,
                       animate-svg-fill-10 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.7000000000000002s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-11 {
          0% {
            stroke-dashoffset: 23.991148575128552px;
            stroke-dasharray: 23.991148575128552px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 23.991148575128552px;
          }
        }
        
        @keyframes animate-svg-stroke-11 {
          0% {
            stroke-dashoffset: 23.991148575128552px;
            stroke-dasharray: 23.991148575128552px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 23.991148575128552px;
          }
        }
        
        .svg-elem-11 {
          -webkit-animation: animate-svg-stroke-11 2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2s both,
                               animate-svg-fill-11 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.8s both;
                  animation: animate-svg-stroke-11 2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2s both,
                       animate-svg-fill-11 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.8s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-12 {
          0% {
            stroke-dashoffset: 23.991148575128552px;
            stroke-dasharray: 23.991148575128552px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 23.991148575128552px;
          }
        }
        
        @keyframes animate-svg-stroke-12 {
          0% {
            stroke-dashoffset: 23.991148575128552px;
            stroke-dasharray: 23.991148575128552px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 23.991148575128552px;
          }
        }
        
        .svg-elem-12 {
          -webkit-animation: animate-svg-stroke-12 2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3199999999999998s both,
                               animate-svg-fill-12 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.9000000000000001s both;
                  animation: animate-svg-stroke-12 2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3199999999999998s both,
                       animate-svg-fill-12 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.9000000000000001s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-13 {
          0% {
            stroke-dashoffset: 23.991148575128552px;
            stroke-dasharray: 23.991148575128552px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 23.991148575128552px;
          }
        }
        
        @keyframes animate-svg-stroke-13 {
          0% {
            stroke-dashoffset: 23.991148575128552px;
            stroke-dasharray: 23.991148575128552px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 23.991148575128552px;
          }
        }
        
        .svg-elem-13 {
          -webkit-animation: animate-svg-stroke-13 2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.44s both,
                               animate-svg-fill-13 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2s both;
                  animation: animate-svg-stroke-13 2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.44s both,
                       animate-svg-fill-13 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-14 {
          0% {
            stroke-dashoffset: 23.991148575128552px;
            stroke-dasharray: 23.991148575128552px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 23.991148575128552px;
          }
        }
        
        @keyframes animate-svg-stroke-14 {
          0% {
            stroke-dashoffset: 23.991148575128552px;
            stroke-dasharray: 23.991148575128552px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 23.991148575128552px;
          }
        }
        
        .svg-elem-14 {
          -webkit-animation: animate-svg-stroke-14 2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.56s both,
                               animate-svg-fill-14 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.1s both;
                  animation: animate-svg-stroke-14 2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.56s both,
                       animate-svg-fill-14 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.1s both;
        }
        
        @-webkit-keyframes animate-svg-stroke-15 {
          0% {
            stroke-dashoffset: 80.53981633974483px;
            stroke-dasharray: 80.53981633974483px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 80.53981633974483px;
          }
        }
        
        @keyframes animate-svg-stroke-15 {
          0% {
            stroke-dashoffset: 80.53981633974483px;
            stroke-dasharray: 80.53981633974483px;
          }
        
          100% {
            stroke-dashoffset: 0;
            stroke-dasharray: 80.53981633974483px;
          }
        }
        
        .svg-elem-15 {
          -webkit-animation: animate-svg-stroke-15 2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.68s both,
                               animate-svg-fill-15 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.2s both;
                  animation: animate-svg-stroke-15 2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.68s both,
                       animate-svg-fill-15 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.2s both;
        }
        
`}
      </style>
      <svg width="240" height="160" viewBox="0 0 240 160" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect x="0.5" y="0.5" width="239" height="159" stroke="#43DCA5" className="svg-elem-1"></rect>
        <line y1="9.19629" x2="240" y2="9.19629" stroke="#43DCA5" className="svg-elem-2"></line>
        <circle cx="6.07516" cy="5.06332" r="1.01266" fill="#43DCA5" className="svg-elem-3"></circle>
        <circle cx="11.1396" cy="5.06332" r="1.01266" fill="#43DCA5" className="svg-elem-4"></circle>
        <circle cx="15.1904" cy="5.06332" r="1.01266" fill="#43DCA5" className="svg-elem-5"></circle>
        <circle cx="126.966" cy="78.9658" r="38.4658" stroke="#43DCA5" className="svg-elem-6"></circle>
        <line x1="152.191" y1="108.458" x2="180.379" y2="136.646" stroke="#26D7A0" className="svg-elem-7"></line>
        <circle cx="37" cy="46" r="3.5" stroke="#26D7A0" className="svg-elem-8"></circle>
        <circle cx="76" cy="74" r="3.5" stroke="#26D7A0" className="svg-elem-9"></circle>
        <circle cx="100" cy="34" r="3.5" stroke="#26D7A0" className="svg-elem-10"></circle>
        <circle cx="186" cy="63" r="3.5" stroke="#26D7A0" className="svg-elem-11"></circle>
        <circle cx="182" cy="30" r="3.5" stroke="#26D7A0" className="svg-elem-12"></circle>
        <circle cx="216" cy="44" r="3.5" stroke="#26D7A0" className="svg-elem-13"></circle>
        <circle cx="24" cy="91" r="3.5" stroke="#26D7A0" className="svg-elem-14"></circle>
        <circle cx="127" cy="78" r="12.5" stroke="#F85E60" strokeWidth="5" className="svg-elem-15"></circle>
      </svg>

    </>
  )
}

export default DeathDashboard
