/* eslint-disable max-len */
import * as React from "react"

const KillingAlert = () => {

  return (
    <>
      <style>
        {`
      /***************************************************
       * Generated by SVG Artista on 9/10/2022, 9:41:17 PM
       * MIT license (https://opensource.org/licenses/MIT)
       * W. https://svgartista.net
       **************************************************/
      
      svg .svg-elem-1 {
        stroke-dashoffset: 426.9996032714844px;
        stroke-dasharray: 426.9996032714844px;
        -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s,
                              fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s;
                transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s,
                      fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s;
      }
      
      svg.active .svg-elem-1 {
        stroke-dashoffset: 0;
      }
      
      svg .svg-elem-2 {
        stroke-dashoffset: 280.7791748046875px;
        stroke-dasharray: 280.7791748046875px;
        -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s,
                              fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s;
                transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s,
                      fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s;
      }
      
      svg.active .svg-elem-2 {
        stroke-dashoffset: 0;
      }
      
      svg .svg-elem-3 {
        stroke-dashoffset: 20.84955592153876px;
        stroke-dasharray: 20.84955592153876px;
        -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s,
                              fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s;
                transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s,
                      fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s;
      }
      
      svg.active .svg-elem-3 {
        stroke-dashoffset: 0;
      }
      
      svg .svg-elem-4 {
        stroke-dashoffset: 20.84955592153876px;
        stroke-dasharray: 20.84955592153876px;
        -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s,
                              fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s;
                transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s,
                      fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s;
      }
      
      svg.active .svg-elem-4 {
        stroke-dashoffset: 0;
      }
      
      svg .svg-elem-5 {
        stroke-dashoffset: 20.84955592153876px;
        stroke-dasharray: 20.84955592153876px;
        -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.48s,
                              fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2000000000000002s;
                transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.48s,
                      fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2000000000000002s;
      }
      
      svg.active .svg-elem-5 {
        stroke-dashoffset: 0;
      }
      
      svg .svg-elem-6 {
        stroke-dashoffset: 191.68606567382812px;
        stroke-dasharray: 191.68606567382812px;
        -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.6s,
                              fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3s;
                transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.6s,
                      fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3s;
      }
      
      svg.active .svg-elem-6 {
        stroke-dashoffset: 0;
      }
      
      svg .svg-elem-7 {
        stroke-dashoffset: 225.62741088867188px;
        stroke-dasharray: 225.62741088867188px;
        -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.72s,
                              fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4000000000000001s;
                transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.72s,
                      fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4000000000000001s;
      }
      
      svg.active .svg-elem-7 {
        stroke-dashoffset: 0;
      }
      
      svg .svg-elem-8 {
        stroke-dashoffset: 8.051612854003906px;
        stroke-dasharray: 8.051612854003906px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.84s,
                              fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.5s;
                transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.84s,
                      fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.5s;
      }
      
      svg.active .svg-elem-8 {
        stroke-dashoffset: 0;
        fill: rgb(38, 215, 160);
      }
      
      svg .svg-elem-9 {
        stroke-dashoffset: 54.012107849121094px;
        stroke-dasharray: 54.012107849121094px;
        fill: transparent;
        -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.96s,
                              fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6s;
                transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.96s,
                      fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6s;
      }
      
      svg.active .svg-elem-9 {
        stroke-dashoffset: 0;
        fill: rgb(38, 215, 160);
      }
      
      svg .svg-elem-10 {
        stroke-dashoffset: 51px;
        stroke-dasharray: 51px;
        -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 1.08s,
                              fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.7000000000000002s;
                transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 1.08s,
                      fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.7000000000000002s;
      }
      
      svg.active .svg-elem-10 {
        stroke-dashoffset: 0;
      }
      
      svg .svg-elem-11 {
        stroke-dashoffset: 15px;
        stroke-dasharray: 15px;
        -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2s,
                              fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.8s;
                transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2s,
                      fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.8s;
      }
      
      svg.active .svg-elem-11 {
        stroke-dashoffset: 0;
      }
      
       
        
`}
      </style>
      <svg width="246" height="182" viewBox="0 0 246 182" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M1 0.629395V180.629H246" stroke="#26D7A0" className="svg-elem-1"></path>
        <path d="M28 120.609L53.9872 146.629L134.883 65.6294L200.689 131.521L225 107.179" stroke="#26D7A0" className="svg-elem-2"></path>
        <circle cx="24.5" cy="117.129" r="3" stroke="#26D7A0" className="svg-elem-3"></circle>
        <circle cx="135.5" cy="60.1294" r="3" stroke="#26D7A0" className="svg-elem-4"></circle>
        <circle cx="228.5" cy="102.129" r="3" stroke="#26D7A0" className="svg-elem-5"></circle>
        <path d="M21 146.629L65 166.129L134 92.6294L169.5 112.629" stroke="#26D7A0" strokeDasharray="2 2" className="svg-elem-6"></path>
        <path d="M96.5 42.6294V14.6294H177V42.6294H142.5L134.5 50.6294L126.5 42.6294H96.5Z" stroke="#26D7A0" className="svg-elem-7"></path>
        <path d="M110.522 33.2192H108.477V34.2H110.522V33.2192Z" fill="#26D7A0" className="svg-elem-8"></path>
        <path d="M113.182 31.65V28.5116C113.182 26.7283 111.802 25.2579 110.011 25.0188V24H108.989V25.0188C107.198 25.2579 105.818 26.7283 105.818 28.5116V31.65H105V32.6308H114V31.65H113.182ZM112.159 31.65H106.841V28.5116C106.841 27.1055 108.034 25.9616 109.5 25.9616C110.966 25.9616 112.159 27.1055 112.159 28.5116V31.65Z" fill="#26D7A0" className="svg-elem-9"></path>
        <line x1="121" y1="26.1294" x2="170" y2="26.1294" stroke="#26D7A0" className="svg-elem-10"></line>
        <line x1="121" y1="30.1294" x2="134" y2="30.1294" stroke="#26D7A0" className="svg-elem-11"></line>
      </svg>


    </>
  )
}

export default KillingAlert
