/* eslint-disable max-len */
import * as React from "react"


const PromiseLand = () => {
  return (
    <>
      <style>
        {`
      /***************************************************
       * Generated by SVG Artista on 9/10/2022, 9:30:10 PM
       * MIT license (https://opensource.org/licenses/MIT)
       * W. https://svgartista.net
       **************************************************/
      
      @-webkit-keyframes animate-svg-stroke-1 {
        0% {
          stroke-dashoffset: 336px;
          stroke-dasharray: 336px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 336px;
        }
      }
      
      @keyframes animate-svg-stroke-1 {
        0% {
          stroke-dashoffset: 336px;
          stroke-dasharray: 336px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 336px;
        }
      }
      
      .svg-elem-1 {
        -webkit-animation: animate-svg-stroke-1 2s linear 0s both,
                             animate-svg-fill-1 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s both;
                animation: animate-svg-stroke-1 2s linear 0s both,
                     animate-svg-fill-1 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-2 {
        0% {
          stroke-dashoffset: 122px;
          stroke-dasharray: 122px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 122px;
        }
      }
      
      @keyframes animate-svg-stroke-2 {
        0% {
          stroke-dashoffset: 122px;
          stroke-dasharray: 122px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 122px;
        }
      }
      
      .svg-elem-2 {
        -webkit-animation: animate-svg-stroke-2 2s linear 0.1s both,
                             animate-svg-fill-2 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s both;
                animation: animate-svg-stroke-2 2s linear 0.1s both,
                     animate-svg-fill-2 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-3 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @keyframes animate-svg-stroke-3 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @-webkit-keyframes animate-svg-fill-3 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      @keyframes animate-svg-fill-3 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      .svg-elem-3 {
        -webkit-animation: animate-svg-stroke-3 2s linear 0.2s both,
                             animate-svg-fill-3 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s both;
                animation: animate-svg-stroke-3 2s linear 0.2s both,
                     animate-svg-fill-3 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-4 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @keyframes animate-svg-stroke-4 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @-webkit-keyframes animate-svg-fill-4 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      @keyframes animate-svg-fill-4 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      .svg-elem-4 {
        -webkit-animation: animate-svg-stroke-4 2s linear 0.30000000000000004s both,
                             animate-svg-fill-4 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s both;
                animation: animate-svg-stroke-4 2s linear 0.30000000000000004s both,
                     animate-svg-fill-4 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-5 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @keyframes animate-svg-stroke-5 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @-webkit-keyframes animate-svg-fill-5 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      @keyframes animate-svg-fill-5 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      .svg-elem-5 {
        -webkit-animation: animate-svg-stroke-5 2s linear 0.4s both,
                             animate-svg-fill-5 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2000000000000002s both;
                animation: animate-svg-stroke-5 2s linear 0.4s both,
                     animate-svg-fill-5 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2000000000000002s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-6 {
        0% {
          stroke-dashoffset: 74px;
          stroke-dasharray: 74px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 74px;
        }
      }
      
      @keyframes animate-svg-stroke-6 {
        0% {
          stroke-dashoffset: 74px;
          stroke-dasharray: 74px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 74px;
        }
      }
      
      .svg-elem-6 {
        -webkit-animation: animate-svg-stroke-6 2s linear 0.5s both,
                             animate-svg-fill-6 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3s both;
                animation: animate-svg-stroke-6 2s linear 0.5s both,
                     animate-svg-fill-6 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-7 {
        0% {
          stroke-dashoffset: 18.26345443725586px;
          stroke-dasharray: 18.26345443725586px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 18.26345443725586px;
        }
      }
      
      @keyframes animate-svg-stroke-7 {
        0% {
          stroke-dashoffset: 18.26345443725586px;
          stroke-dasharray: 18.26345443725586px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 18.26345443725586px;
        }
      }
      
      .svg-elem-7 {
        -webkit-animation: animate-svg-stroke-7 2s linear 0.6000000000000001s both,
                             animate-svg-fill-7 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4000000000000001s both;
                animation: animate-svg-stroke-7 2s linear 0.6000000000000001s both,
                     animate-svg-fill-7 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4000000000000001s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-8 {
        0% {
          stroke-dashoffset: 81px;
          stroke-dasharray: 81px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 81px;
        }
      }
      
      @keyframes animate-svg-stroke-8 {
        0% {
          stroke-dashoffset: 81px;
          stroke-dasharray: 81px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 81px;
        }
      }
      
      .svg-elem-8 {
        -webkit-animation: animate-svg-stroke-8 2s linear 0.7000000000000001s both,
                             animate-svg-fill-8 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.5s both;
                animation: animate-svg-stroke-8 2s linear 0.7000000000000001s both,
                     animate-svg-fill-8 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.5s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-9 {
        0% {
          stroke-dashoffset: 30px;
          stroke-dasharray: 30px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 30px;
        }
      }
      
      @keyframes animate-svg-stroke-9 {
        0% {
          stroke-dashoffset: 30px;
          stroke-dasharray: 30px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 30px;
        }
      }
      
      .svg-elem-9 {
        -webkit-animation: animate-svg-stroke-9 2s linear 0.8s both,
                             animate-svg-fill-9 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6s both;
                animation: animate-svg-stroke-9 2s linear 0.8s both,
                     animate-svg-fill-9 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-10 {
        0% {
          stroke-dashoffset: 336px;
          stroke-dasharray: 336px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 336px;
        }
      }
      
      @keyframes animate-svg-stroke-10 {
        0% {
          stroke-dashoffset: 336px;
          stroke-dasharray: 336px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 336px;
        }
      }
      
      .svg-elem-10 {
        -webkit-animation: animate-svg-stroke-10 2s linear 0.9s both,
                             animate-svg-fill-10 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.7000000000000002s both;
                animation: animate-svg-stroke-10 2s linear 0.9s both,
                     animate-svg-fill-10 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.7000000000000002s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-11 {
        0% {
          stroke-dashoffset: 122px;
          stroke-dasharray: 122px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 122px;
        }
      }
      
      @keyframes animate-svg-stroke-11 {
        0% {
          stroke-dashoffset: 122px;
          stroke-dasharray: 122px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 122px;
        }
      }
      
      .svg-elem-11 {
        -webkit-animation: animate-svg-stroke-11 2s linear 1s both,
                             animate-svg-fill-11 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.8s both;
                animation: animate-svg-stroke-11 2s linear 1s both,
                     animate-svg-fill-11 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.8s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-12 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @keyframes animate-svg-stroke-12 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @-webkit-keyframes animate-svg-fill-12 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      @keyframes animate-svg-fill-12 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      .svg-elem-12 {
        -webkit-animation: animate-svg-stroke-12 2s linear 1.1s both,
                             animate-svg-fill-12 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.9000000000000001s both;
                animation: animate-svg-stroke-12 2s linear 1.1s both,
                     animate-svg-fill-12 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.9000000000000001s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-13 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @keyframes animate-svg-stroke-13 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @-webkit-keyframes animate-svg-fill-13 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      @keyframes animate-svg-fill-13 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      .svg-elem-13 {
        -webkit-animation: animate-svg-stroke-13 2s linear 1.2000000000000002s both,
                             animate-svg-fill-13 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2s both;
                animation: animate-svg-stroke-13 2s linear 1.2000000000000002s both,
                     animate-svg-fill-13 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-14 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @keyframes animate-svg-stroke-14 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @-webkit-keyframes animate-svg-fill-14 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      @keyframes animate-svg-fill-14 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      .svg-elem-14 {
        -webkit-animation: animate-svg-stroke-14 2s linear 1.3s both,
                             animate-svg-fill-14 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.1s both;
                animation: animate-svg-stroke-14 2s linear 1.3s both,
                     animate-svg-fill-14 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.1s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-15 {
        0% {
          stroke-dashoffset: 74px;
          stroke-dasharray: 74px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 74px;
        }
      }
      
      @keyframes animate-svg-stroke-15 {
        0% {
          stroke-dashoffset: 74px;
          stroke-dasharray: 74px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 74px;
        }
      }
      
      .svg-elem-15 {
        -webkit-animation: animate-svg-stroke-15 2s linear 1.4000000000000001s both,
                             animate-svg-fill-15 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.2s both;
                animation: animate-svg-stroke-15 2s linear 1.4000000000000001s both,
                     animate-svg-fill-15 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.2s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-16 {
        0% {
          stroke-dashoffset: 18.26345443725586px;
          stroke-dasharray: 18.26345443725586px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 18.26345443725586px;
        }
      }
      
      @keyframes animate-svg-stroke-16 {
        0% {
          stroke-dashoffset: 18.26345443725586px;
          stroke-dasharray: 18.26345443725586px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 18.26345443725586px;
        }
      }
      
      .svg-elem-16 {
        -webkit-animation: animate-svg-stroke-16 2s linear 1.5s both,
                             animate-svg-fill-16 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.3s both;
                animation: animate-svg-stroke-16 2s linear 1.5s both,
                     animate-svg-fill-16 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.3s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-17 {
        0% {
          stroke-dashoffset: 81px;
          stroke-dasharray: 81px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 81px;
        }
      }
      
      @keyframes animate-svg-stroke-17 {
        0% {
          stroke-dashoffset: 81px;
          stroke-dasharray: 81px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 81px;
        }
      }
      
      .svg-elem-17 {
        -webkit-animation: animate-svg-stroke-17 2s linear 1.6s both,
                             animate-svg-fill-17 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.4000000000000004s both;
                animation: animate-svg-stroke-17 2s linear 1.6s both,
                     animate-svg-fill-17 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.4000000000000004s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-18 {
        0% {
          stroke-dashoffset: 30px;
          stroke-dasharray: 30px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 30px;
        }
      }
      
      @keyframes animate-svg-stroke-18 {
        0% {
          stroke-dashoffset: 30px;
          stroke-dasharray: 30px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 30px;
        }
      }
      
      .svg-elem-18 {
        -webkit-animation: animate-svg-stroke-18 2s linear 1.7000000000000002s both,
                             animate-svg-fill-18 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.5s both;
                animation: animate-svg-stroke-18 2s linear 1.7000000000000002s both,
                     animate-svg-fill-18 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.5s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-19 {
        0% {
          stroke-dashoffset: 276px;
          stroke-dasharray: 276px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 276px;
        }
      }
      
      @keyframes animate-svg-stroke-19 {
        0% {
          stroke-dashoffset: 276px;
          stroke-dasharray: 276px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 276px;
        }
      }
      
      .svg-elem-19 {
        -webkit-animation: animate-svg-stroke-19 2s linear 1.8s both,
                             animate-svg-fill-19 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.6s both;
                animation: animate-svg-stroke-19 2s linear 1.8s both,
                     animate-svg-fill-19 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.6s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-20 {
        0% {
          stroke-dashoffset: 92px;
          stroke-dasharray: 92px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 92px;
        }
      }
      
      @keyframes animate-svg-stroke-20 {
        0% {
          stroke-dashoffset: 92px;
          stroke-dasharray: 92px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 92px;
        }
      }
      
      .svg-elem-20 {
        -webkit-animation: animate-svg-stroke-20 2s linear 1.9000000000000001s both,
                             animate-svg-fill-20 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.7s both;
                animation: animate-svg-stroke-20 2s linear 1.9000000000000001s both,
                     animate-svg-fill-20 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.7s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-21 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @keyframes animate-svg-stroke-21 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @-webkit-keyframes animate-svg-fill-21 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      @keyframes animate-svg-fill-21 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      .svg-elem-21 {
        -webkit-animation: animate-svg-stroke-21 2s linear 2s both,
                             animate-svg-fill-21 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.8s both;
                animation: animate-svg-stroke-21 2s linear 2s both,
                     animate-svg-fill-21 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.8s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-22 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @keyframes animate-svg-stroke-22 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @-webkit-keyframes animate-svg-fill-22 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      @keyframes animate-svg-fill-22 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      .svg-elem-22 {
        -webkit-animation: animate-svg-stroke-22 2s linear 2.1s both,
                             animate-svg-fill-22 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.9000000000000004s both;
                animation: animate-svg-stroke-22 2s linear 2.1s both,
                     animate-svg-fill-22 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 2.9000000000000004s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-23 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @keyframes animate-svg-stroke-23 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @-webkit-keyframes animate-svg-fill-23 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      @keyframes animate-svg-fill-23 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      .svg-elem-23 {
        -webkit-animation: animate-svg-stroke-23 2s linear 2.2s both,
                             animate-svg-fill-23 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3s both;
                animation: animate-svg-stroke-23 2s linear 2.2s both,
                     animate-svg-fill-23 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-24 {
        0% {
          stroke-dashoffset: 74px;
          stroke-dasharray: 74px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 74px;
        }
      }
      
      @keyframes animate-svg-stroke-24 {
        0% {
          stroke-dashoffset: 74px;
          stroke-dasharray: 74px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 74px;
        }
      }
      
      .svg-elem-24 {
        -webkit-animation: animate-svg-stroke-24 2s linear 2.3000000000000003s both,
                             animate-svg-fill-24 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.1000000000000005s both;
                animation: animate-svg-stroke-24 2s linear 2.3000000000000003s both,
                     animate-svg-fill-24 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.1000000000000005s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-25 {
        0% {
          stroke-dashoffset: 18.26345443725586px;
          stroke-dasharray: 18.26345443725586px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 18.26345443725586px;
        }
      }
      
      @keyframes animate-svg-stroke-25 {
        0% {
          stroke-dashoffset: 18.26345443725586px;
          stroke-dasharray: 18.26345443725586px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 18.26345443725586px;
        }
      }
      
      .svg-elem-25 {
        -webkit-animation: animate-svg-stroke-25 2s linear 2.4000000000000004s both,
                             animate-svg-fill-25 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.2s both;
                animation: animate-svg-stroke-25 2s linear 2.4000000000000004s both,
                     animate-svg-fill-25 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.2s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-26 {
        0% {
          stroke-dashoffset: 42px;
          stroke-dasharray: 42px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 42px;
        }
      }
      
      @keyframes animate-svg-stroke-26 {
        0% {
          stroke-dashoffset: 42px;
          stroke-dasharray: 42px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 42px;
        }
      }
      
      .svg-elem-26 {
        -webkit-animation: animate-svg-stroke-26 2s linear 2.5s both,
                             animate-svg-fill-26 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.3s both;
                animation: animate-svg-stroke-26 2s linear 2.5s both,
                     animate-svg-fill-26 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.3s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-27 {
        0% {
          stroke-dashoffset: 30px;
          stroke-dasharray: 30px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 30px;
        }
      }
      
      @keyframes animate-svg-stroke-27 {
        0% {
          stroke-dashoffset: 30px;
          stroke-dasharray: 30px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 30px;
        }
      }
      
      .svg-elem-27 {
        -webkit-animation: animate-svg-stroke-27 2s linear 2.6s both,
                             animate-svg-fill-27 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.4000000000000004s both;
                animation: animate-svg-stroke-27 2s linear 2.6s both,
                     animate-svg-fill-27 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.4000000000000004s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-28 {
        0% {
          stroke-dashoffset: 276px;
          stroke-dasharray: 276px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 276px;
        }
      }
      
      @keyframes animate-svg-stroke-28 {
        0% {
          stroke-dashoffset: 276px;
          stroke-dasharray: 276px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 276px;
        }
      }
      
      .svg-elem-28 {
        -webkit-animation: animate-svg-stroke-28 2s linear 2.7s both,
                             animate-svg-fill-28 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.5s both;
                animation: animate-svg-stroke-28 2s linear 2.7s both,
                     animate-svg-fill-28 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.5s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-29 {
        0% {
          stroke-dashoffset: 92px;
          stroke-dasharray: 92px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 92px;
        }
      }
      
      @keyframes animate-svg-stroke-29 {
        0% {
          stroke-dashoffset: 92px;
          stroke-dasharray: 92px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 92px;
        }
      }
      
      .svg-elem-29 {
        -webkit-animation: animate-svg-stroke-29 2s linear 2.8000000000000003s both,
                             animate-svg-fill-29 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.6000000000000005s both;
                animation: animate-svg-stroke-29 2s linear 2.8000000000000003s both,
                     animate-svg-fill-29 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.6000000000000005s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-30 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @keyframes animate-svg-stroke-30 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @-webkit-keyframes animate-svg-fill-30 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      @keyframes animate-svg-fill-30 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      .svg-elem-30 {
        -webkit-animation: animate-svg-stroke-30 2s linear 2.9000000000000004s both,
                             animate-svg-fill-30 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.7s both;
                animation: animate-svg-stroke-30 2s linear 2.9000000000000004s both,
                     animate-svg-fill-30 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.7s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-31 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @keyframes animate-svg-stroke-31 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @-webkit-keyframes animate-svg-fill-31 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      @keyframes animate-svg-fill-31 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      .svg-elem-31 {
        -webkit-animation: animate-svg-stroke-31 2s linear 3s both,
                             animate-svg-fill-31 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.8s both;
                animation: animate-svg-stroke-31 2s linear 3s both,
                     animate-svg-fill-31 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.8s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-32 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @keyframes animate-svg-stroke-32 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @-webkit-keyframes animate-svg-fill-32 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      @keyframes animate-svg-fill-32 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      .svg-elem-32 {
        -webkit-animation: animate-svg-stroke-32 2s linear 3.1s both,
                             animate-svg-fill-32 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.9000000000000004s both;
                animation: animate-svg-stroke-32 2s linear 3.1s both,
                     animate-svg-fill-32 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 3.9000000000000004s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-33 {
        0% {
          stroke-dashoffset: 74px;
          stroke-dasharray: 74px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 74px;
        }
      }
      
      @keyframes animate-svg-stroke-33 {
        0% {
          stroke-dashoffset: 74px;
          stroke-dasharray: 74px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 74px;
        }
      }
      
      .svg-elem-33 {
        -webkit-animation: animate-svg-stroke-33 2s linear 3.2s both,
                             animate-svg-fill-33 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 4s both;
                animation: animate-svg-stroke-33 2s linear 3.2s both,
                     animate-svg-fill-33 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 4s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-34 {
        0% {
          stroke-dashoffset: 18.26345443725586px;
          stroke-dasharray: 18.26345443725586px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 18.26345443725586px;
        }
      }
      
      @keyframes animate-svg-stroke-34 {
        0% {
          stroke-dashoffset: 18.26345443725586px;
          stroke-dasharray: 18.26345443725586px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 18.26345443725586px;
        }
      }
      
      .svg-elem-34 {
        -webkit-animation: animate-svg-stroke-34 2s linear 3.3000000000000003s both,
                             animate-svg-fill-34 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 4.1000000000000005s both;
                animation: animate-svg-stroke-34 2s linear 3.3000000000000003s both,
                     animate-svg-fill-34 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 4.1000000000000005s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-35 {
        0% {
          stroke-dashoffset: 42px;
          stroke-dasharray: 42px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 42px;
        }
      }
      
      @keyframes animate-svg-stroke-35 {
        0% {
          stroke-dashoffset: 42px;
          stroke-dasharray: 42px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 42px;
        }
      }
      
      .svg-elem-35 {
        -webkit-animation: animate-svg-stroke-35 2s linear 3.4000000000000004s both,
                             animate-svg-fill-35 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 4.2s both;
                animation: animate-svg-stroke-35 2s linear 3.4000000000000004s both,
                     animate-svg-fill-35 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 4.2s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-36 {
        0% {
          stroke-dashoffset: 30px;
          stroke-dasharray: 30px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 30px;
        }
      }
      
      @keyframes animate-svg-stroke-36 {
        0% {
          stroke-dashoffset: 30px;
          stroke-dasharray: 30px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 30px;
        }
      }
      
      .svg-elem-36 {
        -webkit-animation: animate-svg-stroke-36 2s linear 3.5s both,
                             animate-svg-fill-36 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 4.3s both;
                animation: animate-svg-stroke-36 2s linear 3.5s both,
                     animate-svg-fill-36 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 4.3s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-37 {
        0% {
          stroke-dashoffset: 185.2244110107422px;
          stroke-dasharray: 185.2244110107422px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 185.2244110107422px;
        }
      }
      
      @keyframes animate-svg-stroke-37 {
        0% {
          stroke-dashoffset: 185.2244110107422px;
          stroke-dasharray: 185.2244110107422px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 185.2244110107422px;
        }
      }
      
      .svg-elem-37 {
        -webkit-animation: animate-svg-stroke-37 2s linear 3.6s both,
                             animate-svg-fill-37 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 4.4s both;
                animation: animate-svg-stroke-37 2s linear 3.6s both,
                     animate-svg-fill-37 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 4.4s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-38 {
        0% {
          stroke-dashoffset: 62.61260223388672px;
          stroke-dasharray: 62.61260223388672px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 62.61260223388672px;
        }
      }
      
      @keyframes animate-svg-stroke-38 {
        0% {
          stroke-dashoffset: 62.61260223388672px;
          stroke-dasharray: 62.61260223388672px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 62.61260223388672px;
        }
      }
      
      .svg-elem-38 {
        -webkit-animation: animate-svg-stroke-38 2s linear 3.7s both,
                             animate-svg-fill-38 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 4.5s both;
                animation: animate-svg-stroke-38 2s linear 3.7s both,
                     animate-svg-fill-38 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 4.5s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-39 {
        0% {
          stroke-dashoffset: 6.285094680384635px;
          stroke-dasharray: 6.285094680384635px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 6.285094680384635px;
        }
      }
      
      @keyframes animate-svg-stroke-39 {
        0% {
          stroke-dashoffset: 6.285094680384635px;
          stroke-dasharray: 6.285094680384635px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 6.285094680384635px;
        }
      }
      
      @-webkit-keyframes animate-svg-fill-39 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      @keyframes animate-svg-fill-39 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      .svg-elem-39 {
        -webkit-animation: animate-svg-stroke-39 2s linear 3.8000000000000003s both,
                             animate-svg-fill-39 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 4.6000000000000005s both;
                animation: animate-svg-stroke-39 2s linear 3.8000000000000003s both,
                     animate-svg-fill-39 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 4.6000000000000005s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-40 {
        0% {
          stroke-dashoffset: 6.285094680384635px;
          stroke-dasharray: 6.285094680384635px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 6.285094680384635px;
        }
      }
      
      @keyframes animate-svg-stroke-40 {
        0% {
          stroke-dashoffset: 6.285094680384635px;
          stroke-dasharray: 6.285094680384635px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 6.285094680384635px;
        }
      }
      
      @-webkit-keyframes animate-svg-fill-40 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      @keyframes animate-svg-fill-40 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      .svg-elem-40 {
        -webkit-animation: animate-svg-stroke-40 2s linear 3.9000000000000004s both,
                             animate-svg-fill-40 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 4.7s both;
                animation: animate-svg-stroke-40 2s linear 3.9000000000000004s both,
                     animate-svg-fill-40 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 4.7s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-41 {
        0% {
          stroke-dashoffset: 6.285094680384635px;
          stroke-dasharray: 6.285094680384635px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 6.285094680384635px;
        }
      }
      
      @keyframes animate-svg-stroke-41 {
        0% {
          stroke-dashoffset: 6.285094680384635px;
          stroke-dasharray: 6.285094680384635px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 6.285094680384635px;
        }
      }
      
      @-webkit-keyframes animate-svg-fill-41 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      @keyframes animate-svg-fill-41 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      .svg-elem-41 {
        -webkit-animation: animate-svg-stroke-41 2s linear 4s both,
                             animate-svg-fill-41 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 4.8s both;
                animation: animate-svg-stroke-41 2s linear 4s both,
                     animate-svg-fill-41 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 4.8s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-42 {
        0% {
          stroke-dashoffset: 49.18359375px;
          stroke-dasharray: 49.18359375px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 49.18359375px;
        }
      }
      
      @keyframes animate-svg-stroke-42 {
        0% {
          stroke-dashoffset: 49.18359375px;
          stroke-dasharray: 49.18359375px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 49.18359375px;
        }
      }
      
      .svg-elem-42 {
        -webkit-animation: animate-svg-stroke-42 2s linear 4.1000000000000005s both,
                             animate-svg-fill-42 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 4.9s both;
                animation: animate-svg-stroke-42 2s linear 4.1000000000000005s both,
                     animate-svg-fill-42 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 4.9s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-43 {
        0% {
          stroke-dashoffset: 12.95301628112793px;
          stroke-dasharray: 12.95301628112793px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 12.95301628112793px;
        }
      }
      
      @keyframes animate-svg-stroke-43 {
        0% {
          stroke-dashoffset: 12.95301628112793px;
          stroke-dasharray: 12.95301628112793px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 12.95301628112793px;
        }
      }
      
      .svg-elem-43 {
        -webkit-animation: animate-svg-stroke-43 2s linear 4.2s both,
                             animate-svg-fill-43 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 5s both;
                animation: animate-svg-stroke-43 2s linear 4.2s both,
                     animate-svg-fill-43 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 5s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-44 {
        0% {
          stroke-dashoffset: 28.939002990722656px;
          stroke-dasharray: 28.939002990722656px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 28.939002990722656px;
        }
      }
      
      @keyframes animate-svg-stroke-44 {
        0% {
          stroke-dashoffset: 28.939002990722656px;
          stroke-dasharray: 28.939002990722656px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 28.939002990722656px;
        }
      }
      
      .svg-elem-44 {
        -webkit-animation: animate-svg-stroke-44 2s linear 4.3s both,
                             animate-svg-fill-44 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 5.1s both;
                animation: animate-svg-stroke-44 2s linear 4.3s both,
                     animate-svg-fill-44 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 5.1s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-45 {
        0% {
          stroke-dashoffset: 20.85700225830078px;
          stroke-dasharray: 20.85700225830078px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 20.85700225830078px;
        }
      }
      
      @keyframes animate-svg-stroke-45 {
        0% {
          stroke-dashoffset: 20.85700225830078px;
          stroke-dasharray: 20.85700225830078px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 20.85700225830078px;
        }
      }
      
      .svg-elem-45 {
        -webkit-animation: animate-svg-stroke-45 2s linear 4.4s both,
                             animate-svg-fill-45 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 5.2s both;
                animation: animate-svg-stroke-45 2s linear 4.4s both,
                     animate-svg-fill-45 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 5.2s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-46 {
        0% {
          stroke-dashoffset: 276px;
          stroke-dasharray: 276px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 276px;
        }
      }
      
      @keyframes animate-svg-stroke-46 {
        0% {
          stroke-dashoffset: 276px;
          stroke-dasharray: 276px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 276px;
        }
      }
      
      .svg-elem-46 {
        -webkit-animation: animate-svg-stroke-46 2s linear 4.5s both,
                             animate-svg-fill-46 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 5.3s both;
                animation: animate-svg-stroke-46 2s linear 4.5s both,
                     animate-svg-fill-46 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 5.3s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-47 {
        0% {
          stroke-dashoffset: 92px;
          stroke-dasharray: 92px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 92px;
        }
      }
      
      @keyframes animate-svg-stroke-47 {
        0% {
          stroke-dashoffset: 92px;
          stroke-dasharray: 92px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 92px;
        }
      }
      
      .svg-elem-47 {
        -webkit-animation: animate-svg-stroke-47 2s linear 4.6000000000000005s both,
                             animate-svg-fill-47 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 5.4s both;
                animation: animate-svg-stroke-47 2s linear 4.6000000000000005s both,
                     animate-svg-fill-47 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 5.4s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-48 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @keyframes animate-svg-stroke-48 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @-webkit-keyframes animate-svg-fill-48 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      @keyframes animate-svg-fill-48 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      .svg-elem-48 {
        -webkit-animation: animate-svg-stroke-48 2s linear 4.7s both,
                             animate-svg-fill-48 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 5.5s both;
                animation: animate-svg-stroke-48 2s linear 4.7s both,
                     animate-svg-fill-48 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 5.5s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-49 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @keyframes animate-svg-stroke-49 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @-webkit-keyframes animate-svg-fill-49 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      @keyframes animate-svg-fill-49 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      .svg-elem-49 {
        -webkit-animation: animate-svg-stroke-49 2s linear 4.800000000000001s both,
                             animate-svg-fill-49 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 5.6000000000000005s both;
                animation: animate-svg-stroke-49 2s linear 4.800000000000001s both,
                     animate-svg-fill-49 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 5.6000000000000005s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-50 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @keyframes animate-svg-stroke-50 {
        0% {
          stroke-dashoffset: 8.36273043316848px;
          stroke-dasharray: 8.36273043316848px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 8.36273043316848px;
        }
      }
      
      @-webkit-keyframes animate-svg-fill-50 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      @keyframes animate-svg-fill-50 {
        0% {
          fill: transparent;
        }
      
        100% {
          fill: rgb(67, 220, 165);
        }
      }
      
      .svg-elem-50 {
        -webkit-animation: animate-svg-stroke-50 2s linear 4.9s both,
                             animate-svg-fill-50 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 5.7s both;
                animation: animate-svg-stroke-50 2s linear 4.9s both,
                     animate-svg-fill-50 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 5.7s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-51 {
        0% {
          stroke-dashoffset: 74px;
          stroke-dasharray: 74px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 74px;
        }
      }
      
      @keyframes animate-svg-stroke-51 {
        0% {
          stroke-dashoffset: 74px;
          stroke-dasharray: 74px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 74px;
        }
      }
      
      .svg-elem-51 {
        -webkit-animation: animate-svg-stroke-51 2s linear 5s both,
                             animate-svg-fill-51 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 5.8s both;
                animation: animate-svg-stroke-51 2s linear 5s both,
                     animate-svg-fill-51 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 5.8s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-52 {
        0% {
          stroke-dashoffset: 18.26345443725586px;
          stroke-dasharray: 18.26345443725586px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 18.26345443725586px;
        }
      }
      
      @keyframes animate-svg-stroke-52 {
        0% {
          stroke-dashoffset: 18.26345443725586px;
          stroke-dasharray: 18.26345443725586px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 18.26345443725586px;
        }
      }
      
      .svg-elem-52 {
        -webkit-animation: animate-svg-stroke-52 2s linear 5.1000000000000005s both,
                             animate-svg-fill-52 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 5.9s both;
                animation: animate-svg-stroke-52 2s linear 5.1000000000000005s both,
                     animate-svg-fill-52 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 5.9s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-53 {
        0% {
          stroke-dashoffset: 42px;
          stroke-dasharray: 42px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 42px;
        }
      }
      
      @keyframes animate-svg-stroke-53 {
        0% {
          stroke-dashoffset: 42px;
          stroke-dasharray: 42px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 42px;
        }
      }
      
      .svg-elem-53 {
        -webkit-animation: animate-svg-stroke-53 2s linear 5.2s both,
                             animate-svg-fill-53 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 6s both;
                animation: animate-svg-stroke-53 2s linear 5.2s both,
                     animate-svg-fill-53 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 6s both;
      }
      
      @-webkit-keyframes animate-svg-stroke-54 {
        0% {
          stroke-dashoffset: 30px;
          stroke-dasharray: 30px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 30px;
        }
      }
      
      @keyframes animate-svg-stroke-54 {
        0% {
          stroke-dashoffset: 30px;
          stroke-dasharray: 30px;
        }
      
        100% {
          stroke-dashoffset: 0;
          stroke-dasharray: 30px;
        }
      }
      
      .svg-elem-54 {
        -webkit-animation: animate-svg-stroke-54 2s linear 5.300000000000001s both,
                             animate-svg-fill-54 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 6.1000000000000005s both;
                animation: animate-svg-stroke-54 2s linear 5.300000000000001s both,
                     animate-svg-fill-54 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 6.1000000000000005s both;
      }
      
        
`}
      </style>
      <svg
        width="253"
        height="196"
        viewBox="0 0 253 196"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <rect
          x="0.5"
          y="147.5"
          width="119"
          height="48"
          stroke="#43DCA5"
          className="svg-elem-1"
        ></rect>
        <line
          y1="156.5"
          x2="120"
          y2="156.5"
          stroke="#43DCA5"
          className="svg-elem-2"
        ></line>
        <circle
          cx="6.07516"
          cy="152.063"
          r="1.01266"
          fill="#43DCA5"
          className="svg-elem-3"
        ></circle>
        <circle
          cx="11.1396"
          cy="152.063"
          r="1.01266"
          fill="#43DCA5"
          className="svg-elem-4"
        ></circle>
        <circle
          cx="15.1904"
          cy="152.063"
          r="1.01266"
          fill="#43DCA5"
          className="svg-elem-5"
        ></circle>
        <rect
          x="11.5"
          y="166.5"
          width="18"
          height="18"
          stroke="#26D7A0"
          className="svg-elem-6"
        ></rect>
        <path
          d="M15 176.5L18 179.5L26.5 171"
          stroke="#26D7A0"
          className="svg-elem-7"
        ></path>
        <line
          x1="40"
          y1="171.5"
          x2="119"
          y2="171.5"
          stroke="#43DCA5"
          className="svg-elem-8"
        ></line>
        <line
          x1="40"
          y1="181.5"
          x2="68"
          y2="181.5"
          stroke="#43DCA5"
          className="svg-elem-9"
        ></line>
        <rect
          x="130.5"
          y="147.5"
          width="119"
          height="48"
          stroke="#43DCA5"
          className="svg-elem-10"
        ></rect>
        <line
          x1="130"
          y1="156.5"
          x2="250"
          y2="156.5"
          stroke="#43DCA5"
          className="svg-elem-11"
        ></line>
        <circle
          cx="136.075"
          cy="152.063"
          r="1.01266"
          fill="#43DCA5"
          className="svg-elem-12"
        ></circle>
        <circle
          cx="141.14"
          cy="152.063"
          r="1.01266"
          fill="#43DCA5"
          className="svg-elem-13"
        ></circle>
        <circle
          cx="145.19"
          cy="152.063"
          r="1.01266"
          fill="#43DCA5"
          className="svg-elem-14"
        ></circle>
        <rect
          x="145.5"
          y="166.5"
          width="18"
          height="18"
          stroke="#26D7A0"
          className="svg-elem-15"
        ></rect>
        <path
          d="M149 176.5L152 179.5L160.5 171"
          stroke="#26D7A0"
          className="svg-elem-16"
        ></path>
        <line
          x1="174"
          y1="171.5"
          x2="253"
          y2="171.5"
          stroke="#43DCA5"
          className="svg-elem-17"
        ></line>
        <line
          x1="174"
          y1="181.5"
          x2="202"
          y2="181.5"
          stroke="#43DCA5"
          className="svg-elem-18"
        ></line>
        <rect
          x="33.5"
          y="92.5"
          width="89"
          height="48"
          stroke="#43DCA5"
          className="svg-elem-19"
        ></rect>
        <line
          x1="33"
          y1="101.5"
          x2="123"
          y2="101.5"
          stroke="#43DCA5"
          className="svg-elem-20"
        ></line>
        <circle
          cx="39.0752"
          cy="97.0634"
          r="1.01266"
          fill="#43DCA5"
          className="svg-elem-21"
        ></circle>
        <circle
          cx="44.1396"
          cy="97.0634"
          r="1.01266"
          fill="#43DCA5"
          className="svg-elem-22"
        ></circle>
        <circle
          cx="48.1904"
          cy="97.0634"
          r="1.01266"
          fill="#43DCA5"
          className="svg-elem-23"
        ></circle>
        <rect
          x="44.5"
          y="111.5"
          width="18"
          height="18"
          stroke="#26D7A0"
          className="svg-elem-24"
        ></rect>
        <path
          d="M48 121.5L51 124.5L59.5 116"
          stroke="#26D7A0"
          className="svg-elem-25"
        ></path>
        <line
          x1="73"
          y1="116.5"
          x2="113"
          y2="116.5"
          stroke="#43DCA5"
          className="svg-elem-26"
        ></line>
        <line
          x1="73"
          y1="126.5"
          x2="101"
          y2="126.5"
          stroke="#43DCA5"
          className="svg-elem-27"
        ></line>
        <rect
          x="77.5"
          y="38.5"
          width="89"
          height="48"
          stroke="#43DCA5"
          className="svg-elem-28"
        ></rect>
        <line
          x1="77"
          y1="47.5"
          x2="167"
          y2="47.5"
          stroke="#43DCA5"
          className="svg-elem-29"
        ></line>
        <circle
          cx="83.0752"
          cy="43.0634"
          r="1.01266"
          fill="#43DCA5"
          className="svg-elem-30"
        ></circle>
        <circle
          cx="88.1396"
          cy="43.0634"
          r="1.01266"
          fill="#43DCA5"
          className="svg-elem-31"
        ></circle>
        <circle
          cx="92.1904"
          cy="43.0634"
          r="1.01266"
          fill="#43DCA5"
          className="svg-elem-32"
        ></circle>
        <rect
          x="88.5"
          y="57.5"
          width="18"
          height="18"
          stroke="#26D7A0"
          className="svg-elem-33"
        ></rect>
        <path
          d="M92 67.5L95 70.5L103.5 62"
          stroke="#26D7A0"
          className="svg-elem-34"
        ></path>
        <line
          x1="117"
          y1="62.5"
          x2="157"
          y2="62.5"
          stroke="#43DCA5"
          className="svg-elem-35"
        ></line>
        <line
          x1="117"
          y1="72.5"
          x2="145"
          y2="72.5"
          stroke="#43DCA5"
          className="svg-elem-36"
        ></line>
        <rect
          x="92.1934"
          y="0.5"
          width="59.6122"
          height="32"
          stroke="#43DCA5"
          className="svg-elem-37"
        ></rect>
        <line
          x1="91.6934"
          y1="6.23462"
          x2="152.306"
          y2="6.23462"
          stroke="#43DCA5"
          className="svg-elem-38"
        ></line>
        <circle
          cx="95.7855"
          cy="3.41002"
          r="0.681994"
          fill="#43DCA5"
          className="svg-elem-39"
        ></circle>
        <circle
          cx="99.1957"
          cy="3.41002"
          r="0.681994"
          fill="#43DCA5"
          className="svg-elem-40"
        ></circle>
        <circle
          cx="101.922"
          cy="3.41002"
          r="0.681994"
          fill="#43DCA5"
          className="svg-elem-41"
        ></circle>
        <rect
          x="99.6016"
          y="13.2959"
          width="11.7959"
          height="11.7959"
          stroke="#26D7A0"
          className="svg-elem-42"
        ></rect>
        <path
          d="M101.797 19.8674L103.817 21.8878L109.542 16.1633"
          stroke="#26D7A0"
          className="svg-elem-43"
        ></path>
        <line
          x1="118.633"
          y1="16.3367"
          x2="145.572"
          y2="16.3367"
          stroke="#43DCA5"
          className="svg-elem-44"
        ></line>
        <line
          x1="118.633"
          y1="23.0713"
          x2="137.49"
          y2="23.0713"
          stroke="#43DCA5"
          className="svg-elem-45"
        ></line>
        <rect
          x="127.5"
          y="92.5"
          width="89"
          height="48"
          stroke="#43DCA5"
          className="svg-elem-46"
        ></rect>
        <line
          x1="127"
          y1="101.5"
          x2="217"
          y2="101.5"
          stroke="#43DCA5"
          className="svg-elem-47"
        ></line>
        <circle
          cx="133.075"
          cy="97.0634"
          r="1.01266"
          fill="#43DCA5"
          className="svg-elem-48"
        ></circle>
        <circle
          cx="138.14"
          cy="97.0634"
          r="1.01266"
          fill="#43DCA5"
          className="svg-elem-49"
        ></circle>
        <circle
          cx="142.19"
          cy="97.0634"
          r="1.01266"
          fill="#43DCA5"
          className="svg-elem-50"
        ></circle>
        <rect
          x="138.5"
          y="111.5"
          width="18"
          height="18"
          stroke="#26D7A0"
          className="svg-elem-51"
        ></rect>
        <path
          d="M142 121.5L145 124.5L153.5 116"
          stroke="#26D7A0"
          className="svg-elem-52"
        ></path>
        <line
          x1="167"
          y1="116.5"
          x2="207"
          y2="116.5"
          stroke="#43DCA5"
          className="svg-elem-53"
        ></line>
        <line
          x1="167"
          y1="126.5"
          x2="195"
          y2="126.5"
          stroke="#43DCA5"
          className="svg-elem-54"
        ></line>
      </svg>
    </>
  )
}

export default PromiseLand
